### ISSUE TITLE
[Feature] Installation w/ encrypted home directory

### ISSUE THREAD

**Issue by q-pa** [ghostbsd/ghostbsd-src#113]
It would be nice to be able to choose during installation to have a ZFS-encrypted home directory.

**Comment by ericbsd** [comment]
Any reason to not use templates?

I created temples to be used for a specific reason.

**Comment by q-pa** [comment]
Sorry, I did not know about templates. But I cannot find any information about this.
(I just ran the live version and am only planning my switch to GhostBSD at this point.)

**Comment by q-pa** [comment]
OK, found it. I will close this one and open a new one. Sorry!

**Comment by ericbsd** [comment]
Thanks.

Sorry for this I am the one to blame. I just discovered that the website was outdated. I did update https://www.ghostbsd.org/Support/Bugs_%26_Feature_Request to make sure it points to the new one.

**Comment by q-pa** [comment]
No worries
