### ISSUE TITLE
Opt-out root passphrase for remote access during installation.

### ISSUE THREAD

**Issue by chatk7** [ghostbsd/ghostbsd-src#115]
### Describe the feature or enhancement request

Option to disable remote access during installation of root passphrase.

### Why this request?

security

**Comment by ericbsd** [comment]
Would you explain further? I do not understand what you want.

**Comment by ericbsd** [comment]
ping

**Comment by chatk7** [comment]
I presume the root password set up during installation would enable remote login. So an option there to "Disable' remote login would reduce hacker access from such path.
Correct me if I am wrong.








 On Wednesday, November 3, 2021, 10:11:15 AM PDT, Eric Turgeon ***@***.***> wrote:










Would you explain further? I do not understand what you want.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ericbsd** [comment]
SSH is not enabled, and I do not think there is a way to login other than that, and SSH, by default, does not allow root login. 

I am not aware of another way to log in remotely. If you do know another way, please share.

**Comment by ericbsd** [comment]
The logic does not make sense. On a FreeBSD base system, the root user is always enabled, and it needs a password.

**Comment by chatk7** [comment]
I am not knowledgeable about BSD. Fedora 35 has the remote login disabled during the root password setup. I thought root user can login remotely.

So I learned openssh is disabled and there is no other remote login path in BSD.







 On Monday, November 15, 2021, 03:51:31 AM PST, Eric Turgeon ***@***.***> wrote:










The logic does not make sense. On a FreeBSD base system, the root user is always enabled, and it needs a password.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ericbsd** [comment]
Even with OpenSSH enabled, root login is not allowed by default.

**Comment by chatk7** [comment]
Good thoughts on security, alike TrueOS.








 On Monday, November 15, 2021, 11:24:14 AM PST, Eric Turgeon ***@***.***> wrote:










Even with OpenSSH enabled, root login is not allowed by default.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
