### ISSUE TITLE
Print manager  stops working when selecting printer from database

### ISSUE THREAD

**Issue by Surly-Rider** [ghostbsd/ghostbsd-src#13]
Hi there,

adding a HP printer via print manager works fine. Start changing the existing printer configuration via "manufacture and model". "Selecting printer from database". Search started, printer manager stops working. Printer has been removed and installed again. I can reproduce the behaviour.

GhostBSD has been updated this morning to latest version. Reboot has been executed.

**Comment by ericbsd** [comment]
for hp printer, I recommend to install and use `hplip`.

**Comment by ericbsd** [comment]
I can't reproduce this issue?
