### ISSUE TITLE
[Feature]: initgfx for the automatic configuration of the graphics hardware

### ISSUE THREAD

**Issue by SunilSherkhane** [ghostbsd/ghostbsd-src#130]
### Describe the feature or enhancement request

Please port initgfx for the automatic configuration of the graphics hardware. This is available in HelloSystems which works fine. I don't want t to try installing the HelloSystem as I don't want to mess with my partitions. Without initgfx ghostbsd does not identify the display resolution.

### Why this request?

Without initgfx ghostbsd does not identify the display resolution.

**Comment by ericbsd** [comment]
Your ticket needs a bit more information. 

What is the GPU?

**Comment by ericbsd** [comment]
Looking at #133, the automation for Radeon KMS is not supported yet.

**Comment by ericbsd** [comment]
Devs Note: need to add a similar feature to https://github.com/nomadbsd/NomadBSD/blob/5e42b5143814968f85863d04823fc303d2f3b6df/config/etc/rc.d/initgfx#L271-L288 in ghostbsd/ghostbsd-src.
