### ISSUE TITLE
Update GPT Partition Table information, 2nd copy at the end.

### ISSUE THREAD

**Issue by wb7odyfred** [ghostbsd/ghostbsd-src#14]
_Comment on some other forum port, that related to GhostBSD .ISO file images: partition table_

> Second, your GPT scheme (edit: if GPT you use) on your new disk will be corrupted because the backup header/table won't be at the end of the disk. You will have to mend it after reboot: `**gpart recover ada0**`   Hopefully it is this simple command performed on the disk image.  

Can the **GhostBSD.ISO image be fixed** to NOT HAVE a corrupted partition, by the missing 2nd copy of the partition table  placed at the end of the disk?  The GhostBSD 20.09.xx image that is written to a USB Flash Drive.   When booting up it throws a message about a corrupted partition image on the disk.  Not a good message for a new user to see when trying out a live image of GhostBSD.

**Comment by ericbsd** [comment]
That is a FreeBSD related problem

**Comment by wb7odyfred** [comment]
[Wikipedia GUID Partition Table](https://en.wikipedia.org/wiki/GUID_Partition_Table)
Look at secondary GPT on this image.  That is what your .ISO or .IMG  file is missing, Eric.

[GUI Paritiont Table Scheme](https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/GUID_Partition_Table_Scheme.svg/240px-GUID_Partition_Table_Scheme.svg.png)

[Opensense Forum detailed GPT description](https://forum.opnsense.org/index.php?topic=5121.0)
Workaround uses 4 partition 3 good ones, and add 4th partition entry fo,r 512k SWAP partition.
Read the details, very good to describe image versus written into device with 32GB; the second backup partition at the end of the 32Gig USB 'DISK' not at the end of the 9gig 'image'.    

I will research more to find utility application that correctly writes a bootable image using GhostBSD O/S to write to a USB device.

**Comment by ericbsd** [comment]
It is a problem coming from FreeBSD I won't be able to fix.
