### ISSUE TITLE
[Feature]: Customize /etc/os-release

### ISSUE THREAD

**Issue by micahcochran** [ghostbsd/ghostbsd-src#141]
### Describe the feature or enhancement request

This is just to let you know that you might want to customize the `/etc/os-release` file.  This file describes the Operating System.  See man page os-release(5) for more information about the format. It currently says that this is FreeBSD-13.0 STABLE.

### Why this request?

GhostBSD seems to be a a distinct Operating System that is different from FreeBSD.  In my opinion, should be identified as differently.

### Additional context

Here's what a current version outputs:
```
micah@micah-ghostbsd-pc ~> cat /etc/os-release 
NAME=FreeBSD
VERSION=13.0-STABLE
VERSION_ID=13.0
ID=freebsd
ANSI_COLOR="0;31"
PRETTY_NAME="FreeBSD 13.0-STABLE"
CPE_NAME=cpe:/o:freebsd:freebsd:13.0
HOME_URL=https://FreeBSD.org/
BUG_REPORT_URL=https://bugs.FreeBSD.org/
```

**Comment by micahcochran** [comment]
It looks like this file is generated by another file: https://github.com/ghostbsd/ghostbsd-src/blob/main/libexec/rc/rc.d/os-release

**Comment by ericbsd** [comment]
I never notice that before.

**Comment by ericbsd** [comment]
Thanks, I will investigate what uses that file.

**Comment by ericbsd** [comment]
Thank you for this ticket.
```
> distro
Name: FreeBSD 13.0-STABLE
Version: 13.0
Codename: 
```
vs
```
> distro
Name: GhostBSD 21.12.05
Version: 21.12.05 (ISO-Rolling)
Codename: ISO-Rolling
```
![image](https://user-images.githubusercontent.com/4249848/146648485-21959892-7d31-43f8-bc73-c66fff857f4a.png)

**Comment by ericbsd** [comment]
It fixes neofetch OS. 
![image](https://user-images.githubusercontent.com/4249848/146649378-00587a94-475a-4aa8-ac86-8ddefb5ca701.png)

This ticket is related to #75 also
