### ISSUE TITLE
[Bug]: pkg upgrade fails

### ISSUE THREAD

**Issue by Coderdreams** [ghostbsd/ghostbsd-src#148]
### Describe the bug

When executing pkg upgrade, I get the error:

pkg: http://pkg.us.ghostbsd.org/stable/FreeBSD:13:amd64/latest/All/zstd-1.5.1.pkg: Not Found

### How to reproduce the bug?

Execute # sudo pkg upgrade

### Expected behavior

Upgrade succesful

**Comment by ericbsd** [comment]
Not a bug the server was syncing the new packages.

**Comment by Coderdreams** [comment]
Right, it worked now. Thanks

**Comment by ericbsd** [comment]
I made an Epic ticket with some tasks to solve this issue at the GUI level.
