### ISSUE TITLE
[Bug]: missing usernames on login screen

### ISSUE THREAD

**Issue by aeakii** [ghostbsd/ghostbsd-src#156]
### Describe the bug

![Imagepipe_0](https://user-images.githubusercontent.com/97135602/152048914-b2f69ed6-7d65-4262-98f2-a8068c5310cf.jpg)
Ghostbsd 22.01.12 mate 1.26.0
Freebsd 13.0 - STABLE GENERIC amd64

### How to reproduce the bug?

Just install the os

### Expected behavior

I was expecting to see usernames

**Comment by ericbsd** [comment]
So you installed GhostBSD, and you got three users with the name User &?

Your step to reproduce the issue is vague "Just install the os". I tested the installation before the release, and it was working perfectly.

I can't fix it without more in formation.

**Comment by meciks** [comment]
It's possible that I used `pkg update && pkg upgrade` before i saw this bug

**Comment by ericbsd** [comment]
2 users reporting the same issue?

That's confusing.

**Comment by meciks** [comment]
Sry it's my second acc

**Comment by ericbsd** [comment]
So if you did upgrade using `pkg update && pkg upgrade` that is most likely the problem.

System upgrade should be performed with Update Station. There was a kernel change update and using a `pkg upgrade` will most likely break your system if you do not know what you are doing.

**Comment by meciks** [comment]
i've installed it again in vbox and real machine. 
now login screen shows usernames on the real machine
vbox machine after fresh installation:
https://ibb.co/4NM8pw3
it happends randomly during os installation
[https://ibb.co/4NM8pw3](https://ibb.co/4NM8pw3)

**Comment by ericbsd** [comment]
After  or before

**Comment by meciks** [comment]
https://bsd-hardware.info/?probe=1137101df3

**Comment by ericbsd** [comment]
What is the username and then name of the user you use to set up the user?

I will need that in case there is something with parsing the username.

**Comment by ericbsd** [comment]
I also need the full steps for starting the installer to stating the installation.

**Comment by ericbsd** [comment]
I can't reproduce with the latest development ISO.

**Comment by ericbsd** [comment]
I cant fix what I can't reproduce.
