### ISSUE TITLE
[Feature]:   Add Entry for Windows,  How to write a USB Flash Drive

### ISSUE THREAD

**Issue by wb7odyfred** [ghostbsd/ghostbsd-src#158]
### Describe the feature or enhancement request

There are 2 or more tools to write/burn a  GhostBSD.iso file into a USB Flash Drive of 4GB or bigger.
[etcher.io](etcher.io) 70+ Mbyte size with a very simple confindence building interface:  1.) .ISO Filename  2.) USB Flash  drive or SD Flash device to write.  3.)   Flash the device with the .iso file.

or  [rufus.ie](rufus.ie) 4.5 Mbyte size Quick, Easy, Fast, Many options   [https://github.com/pbatard/rufus](https://github.com/pbatard/rufus)  The Open Source Website for Rufus.  [https://www.partitionwizard.com/partitionmanager/is-rufus-safe.html](https://www.partitionwizard.com/partitionmanager/is-rufus-safe.html)   

Welcome other suggestions for USB Writer Tools,  Like UnetBootin    [https://unetbootin.github.io/](https://unetbootin.github.io/)
See their respective documentation to use these three tools above. 

[https://www.tech21century.com/rufus-alternative-software/](https://www.tech21century.com/rufus-alternative-software/)  Comparison of 15 USB Writer Tools.

![GhostBSD_Write_USB_Stick_screen](https://user-images.githubusercontent.com/8184041/152092306-d472af26-f0d6-4940-9ae2-814ac1b2a260.png)

### Why this request?

Some people come from a Windows centric back ground and can use a "Howto" to write a GhostBSD-22.01.29.iso file to a USB Flash drive of Greater than > 4G. 

### Additional context

Welcome other USB Writer Tools,  Like UnetBootin    [https://unetbootin.github.io/](https://unetbootin.github.io/)

**Comment by ericbsd** [comment]
I will add Windows dd steps in the release announcement, but Etcher and Rufus should be added in the documentation.

**Comment by ericbsd** [comment]
Since dd exists for Windows, it might be simple to describe dd.
 ./dd.exe if=GhostBSD-22.01.12.iso of=USB Drive bs=8M

http://www.chrysocome.net/downloads/dd-0.5.zip seems to be the place to download.

http://www.chrysocome.net//dd

https://www.techwalla.com/articles/how-to-use-dd-for-windows-to-make-a-bootable-usb

**Comment by ericbsd** [comment]
Added in the 22.06.15 announcement.
