### ISSUE TITLE
[Bug]: add zfskeys_enable parameter to /etc/defaults/rc.conf

### ISSUE THREAD

**Issue by OuailleAimeScier** [ghostbsd/ghostbsd-src#160]
### Describe the bug

According to this FreeBSD ticket the /etc/defaults/rc.conf file needs a zfskeys_enable parameter to avoid a warning message on boot.

### How to reproduce the bug?

[https://bugs.freebsd.org/bugzilla//show_bug.cgi?id=260301](url)

### Expected behavior

_

**Comment by grahamperrin** [comment]
Thank you. 

Nit, a link typo: 

> `https://github.com/ghostbsd/ghostbsd-src/issues/url`

– should have been: 

FreeBSD bug [260301 – rc.d/zfskeys: missing default value in /etc/defaults/rc.conf](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=260301)

**Comment by ericbsd** [comment]
New OS packages are getting built with rust 1.58.1 to fix #159 http://builder2.ghostbsd.org/build.html?mastername=ghostbsd-13-ghostbsd-ports&build=2022-02-03_21h24m53s

**Comment by ericbsd** [comment]
Updated sent
