### ISSUE TITLE
[Security]: Ensuring minimal security of working with packages

### ISSUE THREAD

**Issue by velogonshik** [ghostbsd/ghostbsd-src#162]
### Describe the feature or enhancement request

it is necessary to use https and package signatures must be used pkg.us.ghostbsd.org

### Why this request?

Ensuring minimal security of working with packages.

**Comment by ericbsd** [comment]
GhostBSD packages are now signed, and I test the certification.

The Canadian, French, and African mirrors now support SSL certification.

I update GhostBSD.conf to point to the Canadian mirror. Unfortunately, there is no US mirror at the moment it pointing to the Canadian one.

An OS package build is in progress to enable the certification for packages in /etc/pkg/GhostBSD.conf.

After the next update, packages certification will be enabled.

The next step is to update https://github.com/ghostbsd/ghostbsd-pkg-conf.

**Comment by ericbsd** [comment]
Everything is completed
