### ISSUE TITLE
After install system doesn't boot from HD on MacOS Parallels, Vmware Fusion or VirtualBox

### ISSUE THREAD

**Issue by rfcosta** [ghostbsd/ghostbsd-src#17]
After install system doesn't boot from HD on MacOS Parallels, Vmware Fusion or VirtualBox
No boot loader found when starting from the freshly installed virtual disk on any of the Virtualization platforms on MacOS Catalina.
I've tried Parallels, Vmware Fusion, Virtual Box. The results or lack of it are the same.
Please advice how to rebuild the boot loader.
If starts from live CD with no problem on Parallells, VMWare fusion and VirtualBox.
Found some reports install misinterpreting disk geometry therefore writing the boot loader on the wrong place. But this last statement I wasnt able to confirm.
Thank you, Reginaldo Costa.

**Comment by ericbsd** [comment]
I might sound ignorant but is Parallels?

**Comment by ericbsd** [comment]
I have no equipment to test that so I will close this.
