### ISSUE TITLE
[Bug]: Software Station - Search blocks entry after two letters

### ISSUE THREAD

**Issue by manfredu** [ghostbsd/ghostbsd-src#174]
### Describe the bug

When searching for a package within Sofware Station the search starts after two letters and this blocks the entry field. It is only possible to continue entering the search string when the search for the two letters has finished.

The issue is that Software Station already starts searching when I'm not yet finished typing. And with 2 letters the search result is of course bigger than necessary. 

### How to reproduce the bug?

E.g. try to find a package for the financial application Gnucash. After typing "gn" one has to wait until the search for "gn" has finished. Then you can continue typing. Of course the second search is much faster and the first search after the entry of gn is completely unnecessary and annoying. 

### Expected behavior

The expected behavior is that Software Station waits with searching until the entry of the search term has finished. Or a least that the user can continue typing while the search is running in the background.

I don't know if it is possible to wait with searching until keyboard entry has stopped for a moment. Or add an additional ui element which starts the search.

Or start the search in a separate thread so that the user can continue to enter the search string. And when the search string has changed interrupt it and start a new search...

**Comment by github12101** [comment]
Confirming this. Search is totally slow because of this bug.
