### ISSUE TITLE
[Bug]: The Lenovo IdeaPad 3 15ITL6 does not detect the WiFi chip 

### ISSUE THREAD

**Issue by anvaralimov** [ghostbsd/ghostbsd-src#183]
### Version

22.01.12

### Explain the issue and what happens

I installed the GhostBSD system on my laptop and started using it. but I can't connect to the Wifi network. The reason is that ghostbsd does not accept my wifi chip 

### Explain how to reproduce the bug?

You need to add a wifi chip driver

**Comment by ericbsd** [comment]
I am not a FreeBSD driver developer. Therefore, it should be reported to FreeBSD, not GhostBSD.
