### ISSUE TITLE
[BUG] Nvidia M4100 no longer detecting after update....

### ISSUE THREAD

**Issue by rgotest** [ghostbsd/ghostbsd-src#185]
### Version

22.04.06

### Explain the issue and what happens

After update X will no longer see monitors using M4100 graphics card on laptop

### Explain how to reproduce the bug?

Update and you will lose all monitors

### What is the Expected behavior (if applicable)

Detect devices connected

**Comment by ericbsd** [comment]
Saying "Update and you will lose all monitors" it is not helpful at all. I am running on Nvidia all also and I didn't have that problem.

So did you use pkg command line to upgrade or Update Station?
