### ISSUE TITLE
Nvidia Geforce GT 630  install not work

### ISSUE THREAD

**Issue by wintstar** [ghostbsd/ghostbsd-src#189]
### Version

22.05..03

### Explain the issue and what happens

I wanted to install GhostBSD. But only the shell input appeared. No error message I could see. I have used this ISO GhostBSD-22.04.22-XFCE.iso. Then I removed my graphics card and ran the installation with the onboard graphics card. With this I was able to install GhostBSD. Then I reinstalled the Nvidia card and manually installed the appropriate driver. So now I can use GhostBSD.

### Explain how to reproduce the bug?

Expansion of the Nvidia graphics card GeForce GT 630.

### Additional context (if applicable)

https://forums.ghostbsd.org/viewtopic.php?p=10592#p10592 (I have been locked out of Telegram. The moment I wanted to reply my internet connection broke and I couldn't send my reply completely anymore).

**Comment by wintstar** [comment]
Same error with the last commit https://github.com/ghostbsd/ghostbsd-src/commit/1fd12ec8237ca7d27357c233bac5931dfe433cab
![bug_nvidia_390](https://user-images.githubusercontent.com/2753863/166834517-74a984d9-54e4-4080-a00c-4da854f9fe20.jpg)

**Comment by ericbsd** [comment]
In regards to Telegraph the captcha bot did kick you. I did unlock you account.

**Comment by wintstar** [comment]
> In regards to Telegraph the captcha bot did kick you. I did unlock you account.

Many thanks :+1:

**Comment by ericbsd** [comment]
Related issue ghostbsd/xconfig#7

**Comment by ericbsd** [comment]
I tested adding the 5 drivers on the system the iso passed from 2.7G to 2.8G.

**Comment by wintstar** [comment]
When an ISO with the changes is ready, I will test it and give feedback.

**Comment by wintstar** [comment]
Tested with [GhostBSD-22.05.13.iso](https://download.ghostbsd.org/development/amd64/latest/GhostBSD-22.05.13.iso) from 13.05.2022. Same error https://forums.ghostbsd.org/viewtopic.php?p=10605#p10605

**Comment by ericbsd** [comment]
That build does not have all the code needed to have it working.

**Comment by ericbsd** [comment]
There is a new iso with the same version, it is ready for testing.

**Comment by wintstar** [comment]
Not work. Only the production driver will be installed. For my graphics card Nvidia GeForce GT 630 the legacy driver 390.147 would have to be installed.
![photo_2022-05-14_16-42-24](https://user-images.githubusercontent.com/2753863/168430693-0839b52b-b846-4652-8325-0e4118ee09f2.jpg)
![photo_2022-05-14_16-45-33](https://user-images.githubusercontent.com/2753863/168430697-b894cfca-b860-402f-b588-2bd52bc19fe4.jpg)

**Comment by wintstar** [comment]
Solved. Problem fixed.

**Comment by ericbsd** [comment]
Thanks for testing and the feedback. I will close the ticket now that it working.
