### ISSUE TITLE
RTL8812AE 802.11ac no driver

### ISSUE THREAD

**Issue by wintstar** [ghostbsd/ghostbsd-src#190]
### Version

22.05.03

### Explain the issue and what happens

Driver for Wlan card Wireless AC1200 Dual Band PCI Express Adapter not found:
DWA-582 https://eu.dlink.com/de/de/products/dwa-582-wireless-ac1200-dual-band-pci-express-adapter 

03:00.0 Network controller [0280]: Realtek Semiconductor Co., Ltd. RTL8812AE 802.11ac PCIe Wireless Network Adapter [10ec:8812] (rev 01)
  Subsystem: D-Link System Inc RTL8812AE 802.11ac PCIe Wireless Network Adapter [1186:3305]
  Kernel driver in use: rtl8821ae
  Kernel modules: rtl8821ae

### Explain how to reproduce the bug?

With the replacement of the DWA 582 Wlan card against an older Ralink Wlan card

**Comment by wintstar** [comment]
I did some research. Since 2017 FreeBSD is dartan to develop a driver. It seems that this development has fallen asleep or the student Mateusz Piotrowski may have lost interest to continue working on it. Please have a look at the links below, maybe the project can be revived or you can find out what the current state of development is. My English and FreeBSD knowledge is not so good that I can go deeper into it.

It would be good if there would be a wifi driver in the foreseeable future. There is a driver for Windows and Linux. But I want to get away from that and rather have GhostBSD / FreeBSD on my PC.

Wouldn't it be possible to compile a Linux driver?

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=237711

https://wiki.freebsd.org/SummerOfCode2017/Porting80211nAnd80211acToFreeBSDiwm

https://wiki.freebsd.org/MateuszPiotrowski/Drivers

https://wiki.freebsd.org/WiFi/Iwlwifi

Sponsoren

https://www.phoronix.com/scan.php?page=news_item&px=802.11ac-FreeBSD-Sponsor

**Comment by ericbsd** [comment]
So far only [Iwlwifi](https://wiki.freebsd.org/WiFi/Iwlwifi) has been ported, and I do not think it is possible to compile other Linux drivers yet.

That would be a question for the FreeBSD Wifi mailing list https://lists.freebsd.org/subscription/freebsd-wireless.
