### ISSUE TITLE
[Feature] BSL similar to wsl

### ISSUE THREAD

**Issue by amitrgholap** [ghostbsd/ghostbsd-src#197]
### Describe the feature or enhancement

Issue with running docker is that we are forced to use vm or linux.
Is it possible to have bsl similar to wsl?
That can be a good 1st step for having docker on gbsd.

### Why this request?

Cannot install n run docker.

**Comment by indgy** [comment]
I would guess that docker support is up to the FreeBSD project. 

FreeBSD has had containers for 22 years now, you could just use those.. checkout BastilleBSD, Pot/Nomad or just plain jails for more details

**Comment by ericbsd** [comment]
@amitrgholap Has @indgy said it is up to FreeBSD, and it is way beyond my knowledge. 

Also, FreeBSD has a Linux emulators layer, but at the moment, it is not working with docker.
