### ISSUE TITLE
[BUG] linux-sublime3-3.2.2_2 not working after upgraded to GhostBSD 22.05.07 amd64

### ISSUE THREAD

**Issue by linunixer** [ghostbsd/ghostbsd-src#199]
### Version

22.05.07

### Explain the issue and what happens

The issue:
under version GhostBSD 22.05.07, tried to open linux-sublime3-3.2.2_2, the window will not be shown up.
Can't find any sublime process in 'ps aux' command.

BTW, now it's upgraded to GhostBSD 22.05.28, still the same

More detail
https://forums.ghostbsd.org/viewtopic.php?f=58&t=2365

### Explain how to reproduce the bug?

1. Install this package linux-sublime3-3.2.2_2
2. Upgrade to GhostBSD 22.05.07 or later
3. Click to Sublime Text icon to open the application

### What is the Expected behavior (if applicable)

After click to open Sublime Text 3.2.2, a sublime text window will be shown up and able to be used.

**Comment by ericbsd** [comment]
I pushed the fix. You should see an update appear soon.

**Comment by linunixer** [comment]
@ericbsd  Thank you for your effort to fix this issue of Linux App!
