### ISSUE TITLE
Video thumbnails support

### ISSUE THREAD

**Issue by danboid** [ghostbsd/ghostbsd-src#202]
I've only tried the MATE build of ghostbsd because that's my fave desktop but I noticed that it doesn't include support for video thumbnails with the default file manager, caja.

This can be enabled for Caja by installing ffmpegthumbnailer. Ghostbsd already includes VLC and hence ffmpeg so adding ffmpegthumbnailer would only be a small addition to the iso. It is also often necessary to edit the Caja preferences to always show thumbnails and for files less that 4 GB under its Preview tab so I'd also be tweaking that to have it on by default.

With Thunar I think it uses tumbler to do this.

**Comment by ericbsd** [comment]
This will be available in the next update.

**Comment by danboid** [comment]
Cool!

Will it be based on FreeBSD 13.x? If not, when will ghostbsd be rebasing on 13.x?

**Comment by ericbsd** [comment]
> Cool!
> 
> 
> 
> Will it be based on FreeBSD 13.x? If not, when will ghostbsd be rebasing on 13.x?

GhostBSD is on 13.1 right now.

**Comment by danboid** [comment]
GhostBSD-22.06.18.iso failed to boot on my laptop.

I've been trying FreeBSD 13.1 today but I've not been able to get the touchpad to work so hopefully the next ghostbsd will boot and have a working touchpad.

**Comment by ericbsd** [comment]
Update pushed.
