### ISSUE TITLE
[BUG] Installation error Device busy

### ISSUE THREAD

**Issue by jlj945** [ghostbsd/ghostbsd-src#203]
### Version

22.06.15

### Explain the issue and what happens

After starting installation, it fails with an error almost immediately.

### Explain how to reproduce the bug?

I just started the installer, continued through it as normal. I tried twice with the same error.

### Additional context (if applicable)

Detaching GELI on ada1p4.eli
Running: geli detach ada1p4.eli
kern.geom.debugflags: 0 -> 16
kern.geom.label.disk_ident.enable: 1 -> 0
Deleting all gparts
Running: gpart destroy -F /dev/ada1
gpart: Device busy
Clearing gpt backup table location on disk
Running: dd if=/dev/zero of=/dev/ada1 bs=1m count=5
5+0 records in
5+0 records out
5242880 bytes transferred in 0.016468 secs (318361519 bytes/sec)
Running: dd if=/dev/zero of=/dev/ada1 bs=1m oseek=114468
dd: /dev/ada1: short write on character device
dd: /dev/ada1: end of device
6+0 records in
5+1 records out
5726208 bytes transferred in 0.020997 secs (272719531 bytes/sec)
Running gpart on /dev/ada1
Running: gpart create -s GPT -f active /dev/ada1
gpart: geom 'ada1': File exists
Running: gpart add -a 4k -s 260M -t efi /dev/ada1
gpart: autofill: No space left on device
Running: newfs_msdos -F 16 /dev/ada1p1
newfs_msdos: /dev/ada1p1: Operation not permitted
Running: gpart add -a 4k -s 111813M -t freebsd-zfs /dev/ada1
gpart: autofill: No space left on device
Running: zpool labelclear -f 
missing vdev name
usage:
	labelclear [-f] <vdev>
Running: gpart add -a 4k -s 2395M -t freebsd-swap /dev/ada1
gpart: autofill: No space left on device
Running: zpool labelclear -f 
missing vdev name
usage:
	labelclear [-f] <vdev>
NEWFS: /dev/ada1p2 - ZFS
Creating storage pool zroot on /dev/ada1p2
Running: zpool create -m none -f zroot /dev/ada1p2
cannot create 'zroot': one or more devices is less than the minimum size (64M)
EXITERROR: ERROR: The partition /dev/ada1p5 does not exist. Failure in bsdlabel?
Running: zfs set mountpoint=/var/tmp zroot/var/tmp
cannot open 'zroot/var/tmp': dataset does not exist
Running: zfs set mountpoint=/var/mail zroot/var/mail
cannot open 'zroot/var/mail': dataset does not exist
Running: zfs set mountpoint=/var/crash zroot/var/crash
cannot open 'zroot/var/crash': dataset does not exist
Running: zfs set mountpoint=/var/audit zroot/var/audit
cannot open 'zroot/var/audit': dataset does not exist
Running: zfs set mountpoint=/var zroot/var
cannot open 'zroot/var': dataset does not exist
Running: zfs set mountpoint=/usr/src zroot/usr/src
cannot open 'zroot/usr/src': dataset does not exist
Running: zfs set mountpoint=/usr/ports zroot/usr/ports
cannot open 'zroot/usr/ports': dataset does not exist
Running: zfs set mountpoint=/usr/home zroot/usr/home
cannot open 'zroot/usr/home': dataset does not exist
Running: zfs set mountpoint=/usr zroot/usr
cannot open 'zroot/usr': dataset does not exist
Running: zfs set mountpoint=/tmp zroot/tmp
cannot open 'zroot/tmp': dataset does not exist
Running: zfs unmount zroot/ROOT/default
cannot open 'zroot/ROOT/default': dataset does not exist
Running: zfs set mountpoint=/ zroot/ROOT/default
cannot open 'zroot/ROOT/default': dataset does not exist
Running: zfs set canmount=noauto zroot/ROOT/default
cannot open 'zroot/ROOT/default': dataset does not exist
Running: swapoff /dev/ada1p5
swapoff: /dev/ada1p5: No such file or directory
Unmounting: /mnt
Running: umount -f /mnt
umount: /mnt: not a file system root directory

**Comment by ericbsd** [comment]
Device busy is most likely your problem. 

What was installed previously? I see Detaching GELI on ada1p4.eli, so I assume you had something like FreeBSD installed.

Most likely, there is something that triggers `Device busy`.

There is also
```
Running: gpart add -a 4k -s 2395M -t freebsd-swap /dev/ada1
gpart: autofill: No space left on device
```

I recommend manually deleting all partitions on your disk and formatting it first.

**Comment by ericbsd** [comment]
Never mind the new automount is to blame.

**Comment by ericbsd** [comment]
Related to issue #204

**Comment by ericbsd** [comment]
I booted the USB and I saw that one partition was automounted, So that is why `Device busy`.

**Comment by ericbsd** [comment]
New ISO under 22.06.18 under https://www.ghostbsd.org/download#latest_builds has a fix for the automount issues.
