### ISSUE TITLE
[BUG] Cannot install GhostBSD on Dell PC Legacy or UEFI

### ISSUE THREAD

**Issue by ChapTechie** [ghostbsd/ghostbsd-src#204]
### Version

22.06.15

### Explain the issue and what happens

I am trying to install GhostBSD on my Dell Optiplex Desktop i7-4770, 24Gb RAM, 120Gb SSD however I tried with the BIOS set to UEFI boot and the installer gives only the Setup FreeBSD boot manager option it will install and upon reboot the Error message no operating system is found is displayed. I added a new Entry in the BIOS to add the BSD hdd as an option but no filename is found. 
I have now set the Dell back to Legacy Boot and this time the installer only gives me the option of FreeBSD loader only but on getting to the point of install the GhostBSD installer crashes out.
[pc-sysinstall.log](https://github.com/ghostbsd/ghostbsd-src/files/8939495/pc-sysinstall.log)

### Explain how to reproduce the bug?

kern.geom.debugflags: 16 -> 16
kern.geom.label.disk_ident.enable: 0 -> 0
Deleting all gparts
Running: gpart destroy -F /dev/ada0
gpart: Device busy
Clearing gpt backup table location on disk
Running: dd if=/dev/zero of=/dev/ada0 bs=1m count=5
5+0 records in
5+0 records out
5242880 bytes transferred in 0.062029 secs (84523254 bytes/sec)
Running: dd if=/dev/zero of=/dev/ada0 bs=1m oseek=114468
dd: /dev/ada0: short write on character device
dd: /dev/ada0: end of device
6+0 records in
5+1 records out
5726208 bytes transferred in 0.011714 secs (488844948 bytes/sec)
Running gpart on /dev/ada0
Running: gpart create -s GPT -f active /dev/ada0
gpart: geom 'ada0': File exists
Running: gpart add -a 4k -s 512 -t freebsd-boot /dev/ada0
ada0p6 added
Running: zpool labelclear -f /dev/ada0p1
failed to open /dev/ada0p1: Operation not permitted
Stamping boot sector on /dev/ada0
Running: gpart bootcode -b /boot/pmbr /dev/ada0
bootcode written to ada0
Running: gpart add -a 4k -s 111912M -t freebsd-zfs /dev/ada0
gpart: autofill: No space left on device
Running: zpool labelclear -f 
missing vdev name
usage:
	labelclear [-f] <vdev>
Running: gpart add -a 4k -s 2556M -t freebsd-swap /dev/ada0
gpart: autofill: No space left on device
Running: zpool labelclear -f 
missing vdev name
usage:
	labelclear [-f] <vdev>
Running: gpart bootcode -b /boot/pmbr -p /boot/gptzfsboot -i 1 /dev/ada0
gpart: /dev/ada0p1: Operation not permitted
NEWFS: /dev/ada0p2 - ZFS
EXITERROR: The poolname: zroot is already in use locally!
Running: zfs set mountpoint=/var/tmp zroot/var/tmp
cannot open 'zroot/var/tmp': dataset does not exist
Running: zfs set mountpoint=/var/mail zroot/var/mail
cannot open 'zroot/var/mail': dataset does not exist
Running: zfs set mountpoint=/var/crash zroot/var/crash
cannot open 'zroot/var/crash': dataset does not exist
Running: zfs set mountpoint=/var/audit zroot/var/audit
cannot open 'zroot/var/audit': dataset does not exist
Running: zfs set mountpoint=/var zroot/var
cannot open 'zroot/var': dataset does not exist
Running: zfs set mountpoint=/usr/src zroot/usr/src
cannot open 'zroot/usr/src': dataset does not exist
Running: zfs set mountpoint=/usr/ports zroot/usr/ports
cannot open 'zroot/usr/ports': dataset does not exist
Running: zfs set mountpoint=/usr/home zroot/usr/home
cannot open 'zroot/usr/home': dataset does not exist
Running: zfs set mountpoint=/usr zroot/usr
cannot open 'zroot/usr': dataset does not exist
Running: zfs set mountpoint=/tmp zroot/tmp
cannot open 'zroot/tmp': dataset does not exist
Running: zfs unmount zroot/ROOT/default
cannot open 'zroot/ROOT/default': dataset does not exist
Running: zfs set mountpoint=/ zroot/ROOT/default
cannot open 'zroot/ROOT/default': dataset does not exist
Running: zfs set canmount=noauto zroot/ROOT/default
cannot open 'zroot/ROOT/default': dataset does not exist
Running: swapoff /dev/ada0p7
swapoff: /dev/ada0p7: No such file or directory
Unmounting: /mnt
Running: umount -f /mnt
umount: /mnt: not a file system root directory

**Comment by ericbsd** [comment]
Could you explain how to reproduce the issue?

Logs go in Additional context.

Without steps, I can't reproduce it and can't fix it.

**Comment by ericbsd** [comment]
Never mind the new automount is to blame.

**Comment by ericbsd** [comment]
New ISO under 22.06.18 under https://www.ghostbsd.org/download#latest_builds has a fix for the automount issues.
