### ISSUE TITLE
Cannot boot or install GhostBSD-22.06.20 on a Lenovo Ideapad 330-17AST

### ISSUE THREAD

**Issue by danboid** [ghostbsd/ghostbsd-src#205]
### Version

22.06.20 XFCE

### Explain the issue and what happens

I have been unable to fully boot or install ghostbsd on my dads Lenovo Ideapad 330-17AST. It only gets as far as you can see in this screenshot:

![ghostbsd-220620-Lenovo-ideapad-330-17ast](https://user-images.githubusercontent.com/1429783/175776376-c3266e7e-6954-4c18-8542-4f8386f8b5ba.jpg)

This error is from the latest XFCE build but I also tried GhostBSD-22.06.18.iso and only got to the same point. I have disabled Secure Boot.

I have been able to successfully install FreeBSD 13.1 and get xorg running on this same laptop so its a ghostbsd specific problem that it fails to load X / start the installer.

I find it odd that ghostbsd (tries to) uninstall virtualbox-ose-additions during boot.

Most everything except for the touchpad and the onboard wifi worked under FreeBSD on this laptop. Does ghostbsd apply some fixes or tweaks to ensure touchpads are more likely to work than under vanilla FreeBSD 13?

### Explain how to reproduce the bug?

Try booting a recent GhostBSD on a Lenovo Ideapad 330-17AST.

### What is the Expected behavior (if applicable)

It should boot and allow me to use the installer.

**Comment by danboid** [comment]
I can boot to X / the installer using NomadBSD on this laptop but the touchpad doesn't work under NomadBSD either.

The latest NomadBSD is still based upon FreeBSD 12.x I think.

**Comment by ericbsd** [comment]
I learned today that all firmware are missing. The new package doesn't install them any more.

**Comment by danboid** [comment]
Yikes!

Let me know when new builds w/ firmware are up please!

**Comment by ericbsd** [comment]
I committed the fix to the problem.

**Comment by danboid** [comment]
Thanks!

When can we expected some updated images with the fix?

**Comment by ericbsd** [comment]
I think it will be today.

**Comment by ericbsd** [comment]
Try the new build 22.06.26 https://www.ghostbsd.org/download#latest_builds.
