### ISSUE TITLE
[Feature] Search also in PKG description (not only PKG name)

### ISSUE THREAD

**Issue by pcu71** [ghostbsd/ghostbsd-src#216]
Software Station does not search within the description of a package.

When using OctoPkg for the same term (e.g. scanner) the user gets a much longer list in OctoPkg as this tool also looks into the description of packages.

It would be nice if the user gets the option to search only within package name, only within the package description, or both.

**Comment by ericbsd** [comment]
I finally got to this. I also added improvements to search and query, which should respond faster.
