### ISSUE TITLE
Using [spacebar] as login password gives "invalid password" when you try to log in

### ISSUE THREAD

**Issue by trampenstein** [ghostbsd/ghostbsd-src#221]
### Version

22.06.18

### Explain the issue and what happens

I used [spacebar] (the spacebar button, not the word) as both root and user password and after the initial reboot, I can't log in as my user when I enter the password. "Invalid password, please try again"

### Explain how to reproduce the bug?

Use single [spacebar] as the password.

### What is the Expected behavior (if applicable)

Be able to log in with the password created at install.

**Comment by trampenstein** [comment]
**Workaround:** enter TTY, sudo passwd _username_ , the [spacebar] works for root password, enter new password for _username_, and use that one to log in. I even "changed" it to [spacebar] and it works after entering it through terminal, just not during initial setup.

**Comment by ericbsd** [comment]
Yeah, I think the installer should not allow that since it is not secure.

**Comment by ericbsd** [comment]
Fixed in the latest build.
