### ISSUE TITLE
[Feature]: Add noto-emoji font or noto fonts in general

### ISSUE THREAD

**Issue by mfjurbala** [ghostbsd/ghostbsd-src#223]
### Describe the feature or enhancement

Add the noto-emoji package to provide emoji coverage expected by many users on modern systems. Optionally, add the noto metapackage in addition to or in place of the current fonts to have the highest font coverage possible.

### Why this request?

Emoji aren't necessary but are everywhere. Going to a site and getting tofu (the square that is shown when you dont have a font character) makes it seem like something is broken. Adding at least the noto-emoji package provides an experience more similar to other popular oerating systems. 

The noto package provides great coverage but is about 2GB. The emoji font only adds about 10MB. There are also variations for the noto package - noto-basic, noto-extra, Chinese, Korean, etc.

**Comment by ericbsd** [comment]
Made a new meta port for fonts https://github.com/ghostbsd/ghostbsd-ports/commit/f1cbbcabc916883e3b9767f9c337ffd2f82e3616

**Comment by ericbsd** [comment]
I will make a change later so that it will be installed by an update.
