### ISSUE TITLE
Memdisk size for the livecd zfs pool is hardcoded to 3GB

### ISSUE THREAD

**Issue by samob** [ghostbsd/ghostbsd-src#225]
### Version

22.03.09

### Explain the issue and what happens

In case user has more than 4GB of RAM on his computer, it would be really usefull to be able to increase memory disk size acording to his hardware. 

### Explain how to reproduce the bug?

At boot time memdisk is created with hardcoded size of 3GB, wich is insufficient in some cases

### What is the Expected behavior (if applicable)

If user has for example 16GB of RAM, size of memdisk could/should be adjusted accordingly.

### Additional context (if applicable)

https://github.com/ghostbsd/ghostbsd-build/blob/60f46b55d9e7d40e062bf0ccf3b4d6d5c5f242d8/init.sh.in#L45-L46

**Comment by ericbsd** [comment]
I have tested some changes. Here is a 16GB VM zfs list.
![image](https://user-images.githubusercontent.com/4249848/185749208-9af36121-c152-4308-8582-6e62f3065718.png)
