### ISSUE TITLE
[BUG] Black screen during installation (Nvidia)

### ISSUE THREAD

**Issue by atlas-devel** [ghostbsd/ghostbsd-src#229]
### Version

22.06.18

### Explain the issue and what happens

Whenever i try to install GhostBSD, i get a black screen after it loads the installation components into memdisk. I can wait however long here, it will not progress. I am running a Nvidia GTX 1650 Super. Whenever i press the button on my computer to turn it off, i get some errors visible on screen, one for "`coudln't access control socket /var/run/user/1001/keyring/control`", and one saying "`failed to register client: GDBus.Error:org.gnome.sessionManager.AlreadyRegistered`"

### Explain how to reproduce the bug?

Try to install GhostBSD 22.06.18 MATE on Nvidia GTX 1650 Super

### What is the Expected behavior (if applicable)

Actually boot to live environment

**Comment by vermaden** [comment]
These are the remaining components:

- Gigabyte Z97-HD3
- Intel i5-4590

... as stated here:

- https://www.reddit.com/r/BSD/comments/xpjekl/best_beginner_bsd_for_desktop_gui_preinstalled/ir541t4/?context=8&depth=9

(maybe it will help to solve it)

Regards.

**Comment by ericbsd** [comment]
@atlas-devel did you try to use the latest build instead of the release?

**Comment by ericbsd** [comment]
It could be related to https://github.com/ghostbsd/ghostbsd-src/issues/225

**Comment by atlas-devel** [comment]
> @atlas-devel did you try to use the latest build instead of the release?

No, i have not, i will try it later
