### ISSUE TITLE
Ghostbsd freezes when trying to boot X- UHD 630 onboard intel VGA.

### ISSUE THREAD

**Issue by FEF7691** [ghostbsd/ghostbsd-src#230]
### Version

22.09.16 XFCE

### Explain the issue and what happens

The boot sequence goes as far as shown in the photo. When he tries to boot X, she freezes and dies.
I have no way to access log files on the flash drive to see what the problem is. 
Cheksum of the iso image checked successfully
The video card is an Intel Corporation CometLake-S GT2 [UHD Graphics 630] (rev 03).
![20220929_090444](https://user-images.githubusercontent.com/104235675/193031088-b07f76fd-1e1f-46e7-8a89-1fb557b8e606.jpg)

### Explain how to reproduce the bug?

Try booting several times by changing pendrive and USB ports.

### What is the Expected behavior (if applicable)

to load the desktop complete.

### Additional context (if applicable)

Motherboard Gigabyte H510M H rev1.0
Intel i3-10105 gen11
8GB Ram
nvme disc

**Comment by ericbsd** [comment]
Did you try the newer latest build?

**Comment by FEF7691** [comment]
I just tried version 23.02.02 and it doesn't work either.
Thank you anyway.

**Comment by ericbsd** [comment]
Is the last build, 23.05.28, fixed the issue? https://www.ghostbsd.org/download#latest_builds

**Comment by FEF7691** [comment]
The same F......n error. Don´t worry Eric, I'm using other OS. 
Thank you.
Best regards.
