### ISSUE TITLE
GhostBSD doesn´t boot X. Nvidia GeForce 210

### ISSUE THREAD

**Issue by FEF7691** [ghostbsd/ghostbsd-src#231]
### Version

22.09.16 XFCE

### Explain the issue and what happens

GhostBSD can´t start X.
Atached the hw-probe info.
https://bsd-hardware.info/?probe=8ad31cc470

### Explain how to reproduce the bug?

Several boots

### What is the Expected behavior (if applicable)

That StartX

**Comment by ericbsd** [comment]
Is this still a problem with our latest ISO?

**Comment by ericbsd** [comment]
This seems to have happened at the same time then my iMac issue with the newer xorg version.

**Comment by ericbsd** [comment]
I found two issues. One looks to be xconfig related, and the second is the new Xorg is not compatible with the old Nvidia ABI.

![Image](https://user-images.githubusercontent.com/4249848/219882450-c803a13d-7558-4bfe-a319-9320cb739d0a.jpg)

The Xorg update did brook old Nvidia drivers. 

There is a solution here https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=266682.

**Comment by FEF7691** [comment]
Hi Eric
I have not tried with the latest, but with the 23.01.13, also without
success.
I'll try it and I'll tell you.
Thank you for your concern.
Kind regards.
Frederick

**Comment by FEF7691** [comment]
It doesn't work with 23.02.02 either. X doesn´t start.
Thank you anyway.

**Comment by ericbsd** [comment]
The problem is here https://github.com/ghostbsd/ghostbsd-src/issues/231#issuecomment-1435735612, and I have a workaround for it.

**Comment by ericbsd** [comment]
I am testing a new configuration on my iMac with the same issue.

**Comment by ericbsd** [comment]
Ok, I fixed the issue on my iMac a new iso will be ready soon.

**Comment by FEF7691** [comment]
Thank you.

**Comment by ericbsd** [comment]
The ISO with the fix https://www.ghostbsd.org/download#latest_builds

**Comment by tim-pearce** [comment]
I tried the update again, this time in the right order. Still does nor work for me.
In particular I see a message going past during startup that there is no nvidia-modeset module available (or something like that - it just flashes past and I can't find it in a log file anywhere).
