### ISSUE TITLE
[BUG] Error ports instalation

### ISSUE THREAD

**Issue by davidmanoel** [ghostbsd/ghostbsd-src#234]
### Version

22.10.12

### Explain the issue and what happens

I'm having an error whan I try to install 'ports'.
After fetching/download and extract step, in the install process, the terminal show the error and it stop, and not installing
![Terminal](https://user-images.githubusercontent.com/113417875/196847451-dae9904a-14de-4dfa-8a6c-132c6438009f.png)

### Explain how to reproduce the bug?

Simply opening the terminal and running the command:

# sudo pkg install ports

The error happens in any situation.

Installing GhostBSD without updating the system, or installing GhostBSD and updating the system.

### What is the Expected behavior (if applicable)

The expected behavior is for ports to install successfully.

### Additional context (if applicable)

About the error explanation shown in the terminal, I thought it would be some error related to the timezone configuration, and I tried to perform all the ways to review and update the highlighted settings. I successfully reconfigured everything and the ports installation error still persists.

I'll try to install ports directly from github and hope for success.

**Comment by ericbsd** [comment]
Thanks for reporting.

**Comment by tim-pearce** [comment]
I get that error, but ports still works. I think it's just that one port that is affected.

**Comment by mfjurbala** [comment]
@tim-pearce and @davidmanoel, did this error still come up on the newest GhostBSD version and what timezone/locale are you using? I just tried on 23.03.17 with EDT and en_US-UTF-8 but didn't get any errors or warnings.

Thanks

**Comment by ericbsd** [comment]
I am not sure what I did or what happened but it is finally fixed on 23.05.28.
