### ISSUE TITLE
[Feature]: Add AppImage support

### ISSUE THREAD

**Issue by hardBSDk** [ghostbsd/ghostbsd-src#238]
### Describe the feature or enhancement

I think helloSystem has this enabled by default (with some bugs on some apps).

https://github.com/helloSystem/hello/wiki/#technology
https://github.com/AppImage/AppImageKit/issues/98#issuecomment-1179724596
https://github.com/AppImage/AppImageKit/issues/98

### Why this request?

Because AppImages are universal, isolated and safe (reducing the surface of attack).

Helping with security/dependency problems.

**Comment by hansw-nlo** [comment]
Can I please ask to reconsider? AppImage is simply taking git hosted projects and not checking the source in any way. I asked the developer why and he simply trusts git for it. 

Imho Appimage, flatpak and/or snaps should never be considered.

**Comment by hardBSDk** [comment]
> Can I please ask to reconsider? AppImage is simply taking git hosted projects and not checking the source in any way. I asked the developer why and he simply trusts git for it.
> 
> Imho Appimage, flatpak and/or snaps should never be considered.

AppImage repository is not maintained by AppImage team, they use a script based on links via Pull Requests, the user need to trust the dev when selecting his software.

When I ask support for AppImage, I want all the dependencies necessary to run any .AppImage out-of-the-box (mostly FUSE).

**Comment by ericbsd** [comment]
I agree with @hansw-nlo here. At least with FreeBSD ports, we do have audits for vulnerability. The thing AppImage, we do not have any verification of vulnerability. If it comes to ports, people will be able to use it, but before then, I will not invest time in that.

**Comment by hansw-nlo** [comment]
I asked the developer about it (no checksums) and he simply stated he trusts git. For me it was a reason to ditch it.

**Comment by ericbsd** [comment]
This will not come on GhostBSD by default.
