### ISSUE TITLE
[Feature]: Add a GNOME flavour

### ISSUE THREAD

**Issue by hardBSDk** [ghostbsd/ghostbsd-src#239]
### Describe the feature or enhancement

Create a image with latest GNOME included.

Would be nice to have a separate flavour for GNOME to be in pair with Linux distributions.

### Why this request?

Because GNOME is one of the best DEs of the world, with simplicity and less-distraction in mind.

**Comment by ericbsd** [comment]
If someone is interested in making it happen, I have no problem with that. The more DE I have to maintain on GhostBSD, the more problem it causes me, and it puts time away to get the missing tool or feature on tools to get done.

Also, Gnome is more like a tablet environment than a desktop environment.

**Comment by hansw-nlo** [comment]
Gnome is slowly switching to install things using Flatpak. One of the reasons for me to leave Linux to be honest. I would not use it again.

**Comment by ericbsd** [comment]
Closing this because there I dought there will be someone to make it happen.
