### ISSUE TITLE
[Bug]: Software Station freezes after cancelling package installation

### ISSUE THREAD

**Issue by mfjurbala** [ghostbsd/ghostbsd-src#240]
### Version

22.10.30

### Explain the issue and what happens

Software Station becomes unresponsive if package installation is cancelled.

### Explain how to reproduce the bug?

Select a package to install in Software Station and click "Apply". In the "Software changes to apply" window, click "Cancel" or the close window button (top right).

### What is the Expected behavior (if applicable)

After cancelling package installation, Software Station should allow the user to continue to search for and install packages.

**Comment by ericbsd** [comment]
Note for me: Looks to only happen on searches.

**Comment by ericbsd** [comment]
```
> sudo software-station
default            192.168.2.1        UGS        igb0
Traceback (most recent call last):
  File "/usr/local/bin/software-station", line 671, in hidewindow
    self.cancel_change(None)
  File "/usr/local/bin/software-station", line 202, in cancel_change
    self.update_search()
TypeError: update_search() missing 1 required positional argument: 'search'
```
