### ISSUE TITLE
[BUG] <title>Intel WiFi 8265/8275 performance issues

### ISSUE THREAD

**Issue by MaDdMiKe0540** [ghostbsd/ghostbsd-src#251]
### Version

22.11.22

### Explain the issue and what happens

Wifi does connect and function just minimal performance may be a driver issue

### Explain how to reproduce the bug?

have tried it on 3 lenovo 7th gen intel bored wtih same wifi cards

### What is the Expected behavior (if applicable)

enough speed to be able to download an ISO from wlan while in field at datacenter and no wake up issues from hacky work arounds. 

### Additional context (if applicable)

helpmywifigo.sh output
 PCI devices configuration list verbose

hostb0@pci0:0:0:0:	class=0x060000 rev=0x02 hdr=0x00 vendor=0x8086 device=0x5904 subvendor=0x17aa subdevice=0x505f
    vendor     = 'Intel Corporation'
    device     = 'Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers'
    class      = bridge
    subclass   = HOST-PCI
vgapci0@pci0:0:2:0:	class=0x030000 rev=0x02 hdr=0x00 vendor=0x8086 device=0x5916 subvendor=0x17aa subdevice=0x505f
    vendor     = 'Intel Corporation'
    device     = 'HD Graphics 620'
    class      = display
    subclass   = VGA
xhci0@pci0:0:20:0:	class=0x0c0330 rev=0x21 hdr=0x00 vendor=0x8086 device=0x9d2f subvendor=0x17aa subdevice=0x505f
    vendor     = 'Intel Corporation'
    device     = 'Sunrise Point-LP USB 3.0 xHCI Controller'
    class      = serial bus
    subclass   = USB
pchtherm0@pci0:0:20:2:	class=0x118000 rev=0x21 hdr=0x00 vendor=0x8086 device=0x9d31 subvendor=0x17aa subdevice=0x505f
    vendor     = 'Intel Corporation'
    device     = 'Sunrise Point-LP Thermal subsystem'
    class      = dasp
none0@pci0:0:22:0:	class=0x078000 rev=0x21 hdr=0x00 vendor=0x8086 device=0x9d3a subvendor=0x17aa subdevice=0x505f
    vendor     = 'Intel Corporation'
    device     = 'Sunrise Point-LP CSME HECI'
    class      = simple comms
ahci0@pci0:0:23:0:	class=0x010601 rev=0x21 hdr=0x00 vendor=0x8086 device=0x9d03 subvendor=0x17aa subdevice=0x505f
    vendor     = 'Intel Corporation'
    device     = 'Sunrise Point-LP SATA Controller [AHCI mode]'
    class      = mass storage
    subclass   = SATA
pcib1@pci0:0:28:0:	class=0x060400 rev=0xf1 hdr=0x01 vendor=0x8086 device=0x9d10 subvendor=0x17aa subdevice=0x505f
    vendor     = 'Intel Corporation'
    device     = 'Sunrise Point-LP PCI Express Root Port'
    class      = bridge
    subclass   = PCI-PCI
pcib2@pci0:0:28:6:	class=0x060400 rev=0xf1 hdr=0x01 vendor=0x8086 device=0x9d16 subvendor=0x17aa subdevice=0x505f
    vendor     = 'Intel Corporation'
    device     = 'Sunrise Point-LP PCI Express Root Port'
    class      = bridge
    subclass   = PCI-PCI
pcib3@pci0:0:29:0:	class=0x060400 rev=0xf1 hdr=0x01 vendor=0x8086 device=0x9d18 subvendor=0x17aa subdevice=0x505f
    vendor     = 'Intel Corporation'
    device     = 'Sunrise Point-LP PCI Express Root Port'
    class      = bridge
    subclass   = PCI-PCI
pcib4@pci0:0:29:3:	class=0x060400 rev=0xf1 hdr=0x01 vendor=0x8086 device=0x9d1b subvendor=0x17aa subdevice=0x505f
    vendor     = 'Intel Corporation'
    class      = bridge
    subclass   = PCI-PCI
isab0@pci0:0:31:0:	class=0x060100 rev=0x21 hdr=0x00 vendor=0x8086 device=0x9d58 subvendor=0x17aa subdevice=0x505f
    vendor     = 'Intel Corporation'
    device     = 'Sunrise Point-LP LPC Controller'
    class      = bridge
    subclass   = PCI-ISA
none1@pci0:0:31:2:	class=0x058000 rev=0x21 hdr=0x00 vendor=0x8086 device=0x9d21 subvendor=0x17aa subdevice=0x505f
    vendor     = 'Intel Corporation'
    device     = 'Sunrise Point-LP PMC'
    class      = memory
hdac0@pci0:0:31:3:	class=0x040300 rev=0x21 hdr=0x00 vendor=0x8086 device=0x9d71 subvendor=0x17aa subdevice=0x505f
    vendor     = 'Intel Corporation'
    device     = 'Sunrise Point-LP HD Audio'
    class      = multimedia
    subclass   = HDA
ichsmb0@pci0:0:31:4:	class=0x0c0500 rev=0x21 hdr=0x00 vendor=0x8086 device=0x9d23 subvendor=0x17aa subdevice=0x505f
    vendor     = 'Intel Corporation'
    device     = 'Sunrise Point-LP SMBus'
    class      = serial bus
    subclass   = SMBus
em0@pci0:0:31:6:	class=0x020000 rev=0x21 hdr=0x00 vendor=0x8086 device=0x15d8 subvendor=0x17aa subdevice=0x505f
    vendor     = 'Intel Corporation'
    device     = 'Ethernet Connection (4) I219-V'
    class      = network
    subclass   = ethernet
rtsx0@pci0:3:0:0:	class=0xff0000 rev=0x01 hdr=0x00 vendor=0x10ec device=0x522a subvendor=0x17aa subdevice=0x505f
    vendor     = 'Realtek Semiconductor Co., Ltd.'
    device     = 'RTS522A PCI Express Card Reader'
iwm0@pci0:5:0:0:	class=0x028000 rev=0x78 hdr=0x00 vendor=0x8086 device=0x24fd subvendor=0x8086 subdevice=0x1010
    vendor     = 'Intel Corporation'
    device     = 'Wireless 8265 / 8275'
    class      = network
\n USB devises configuration list.  Usbconfig dump_device_desc \n
ugen0.1: <Intel XHCI root HUB> at usbus0, cfg=0 md=HOST spd=SUPER (5.0Gbps) pwr=SAVE (0mA)
ugen0.2: <vendor 0x8087 product 0x0a2b> at usbus0, cfg=0 md=HOST spd=FULL (12Mbps) pwr=ON (100mA)
ugen0.3: <Chicony Electronics Co.,Ltd. Integrated Camera> at usbus0, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=ON (500mA)
ugen0.1: <Intel XHCI root HUB> at usbus0, cfg=0 md=HOST spd=SUPER (5.0Gbps) pwr=SAVE (0mA)

  bLength = 0x0012 
  bDescriptorType = 0x0001 
  bcdUSB = 0x0300 
  bDeviceClass = 0x0009  <HUB>
  bDeviceSubClass = 0x0000 
  bDeviceProtocol = 0x0003 
  bMaxPacketSize0 = 0x0009 
  idVendor = 0x0000 
  idProduct = 0x0000 
  bcdDevice = 0x0100 
  iManufacturer = 0x0001  <Intel>
  iProduct = 0x0002  <XHCI root HUB>
  iSerialNumber = 0x0000  <no string>
  bNumConfigurations = 0x0001 

ugen0.2: <vendor 0x8087 product 0x0a2b> at usbus0, cfg=0 md=HOST spd=FULL (12Mbps) pwr=ON (100mA)

  bLength = 0x0012 
  bDescriptorType = 0x0001 
  bcdUSB = 0x0200 
  bDeviceClass = 0x00e0  <Wireless controller>
  bDeviceSubClass = 0x0001 
  bDeviceProtocol = 0x0001 
  bMaxPacketSize0 = 0x0040 
  idVendor = 0x8087 
  idProduct = 0x0a2b 
  bcdDevice = 0x0010 
  iManufacturer = 0x0000  <no string>
  iProduct = 0x0000  <no string>
  iSerialNumber = 0x0000  <no string>
  bNumConfigurations = 0x0001 

ugen0.3: <Chicony Electronics Co.,Ltd. Integrated Camera> at usbus0, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=ON (500mA)

  bLength = 0x0012 
  bDescriptorType = 0x0001 
  bcdUSB = 0x0200 
  bDeviceClass = 0x00ef  <Miscellaneous device>
  bDeviceSubClass = 0x0002 
  bDeviceProtocol = 0x0001 
  bMaxPacketSize0 = 0x0040 
  idVendor = 0x04f2 
  idProduct = 0xb5c0 
  bcdDevice = 0x0005 
  iManufacturer = 0x0003  <Chicony Electronics Co.,Ltd.>
  iProduct = 0x0001  <Integrated Camera>
  iSerialNumber = 0x0002  <0001>
  bNumConfigurations = 0x0001 

 the Kernel loaded modules.  kldunload / kldload commands to remove and add kernel modules

Id Refs Address                Size Name
 1  106 0xffffffff80200000  2940b70 kernel
 2    1 0xffffffff82b42000    1afe8 geom_eli.ko
 3    1 0xffffffff82b5d000   59a660 zfs.ko
 4    1 0xffffffff83cf9000     73b0 linprocfs.ko
 5    4 0xffffffff83d01000     add8 linux_common.ko
 6    1 0xffffffff83d0c000     3284 linsysfs.ko
 7    1 0xffffffff83d10000     3530 fdescfs.ko
 8    1 0xffffffff83d14000    2ec10 linux.ko
 9    1 0xffffffff83d43000    2ae90 linux64.ko
10    1 0xffffffff83d6e000     6730 cuse.ko
11    1 0xffffffff83d75000    11cd8 fusefs.ko
12    1 0xffffffff83d87000   1808b8 i915kms.ko
13    1 0xffffffff83f08000    72bd8 drm.ko
14    1 0xffffffff83f7b000     22b0 iic.ko
15    2 0xffffffff83f7e000     30fc linuxkpi_gplv2.ko
16    3 0xffffffff83f82000     62d8 dmabuf.ko
17    1 0xffffffff83f89000     3378 acpi_wmi.ko
18    1 0xffffffff83f8d000     3250 ichsmb.ko
19    1 0xffffffff83f91000     2180 smbus.ko
20    1 0xffffffff83f94000    880c8 if_iwlwifi.ko
21    1 0xffffffff8401d000    17310 if_iwm.ko
22    1 0xffffffff84035000     2110 pchtherm.ko
23    1 0xffffffff84038000     4cfc geom_uzip.ko
24    1 0xffffffff8403d000     4d00 ng_ubt.ko
25    3 0xffffffff84042000     aac8 netgraph.ko
26    2 0xffffffff8404d000     a238 ng_hci.ko
27    2 0xffffffff84058000     25a8 ng_bluetooth.ko
28    1 0xffffffff8405b000    27190 ipfw.ko
29    1 0xffffffff84083000     2260 pty.ko
30    1 0xffffffff84086000     2a08 mac_ntpd.ko

 Read Networking Forum posts  https://forums.ghostbsd.org/viewtopic.php?f=64&t=16

Read USB wifi device Edimax EW-7811 post & PCI wifi device RTL8188CE post
 
PCI device RealTek RLT8188CE https://forums.ghostbsd.org/viewtopic.php?f=64&t=570 

USB device Edimax EW-7811un https://forums.ghostbsd.org/viewtopic.php?f=64&t=526 

 or read the PDF format of these files located here /usr/share/doc/?xxxx? for examples of setting up wifi.

  Now output these 3 files /boot/loader.conf, /etc/rc.conf, and /etc/wpa_supplicant.conf

 /boot/loader.con  contents: 

rc_system="bsdrc"
crypto_load="YES"
aesni_load="YES"
geom_eli_load="YES"
vfs.zfs.arc_max="512M"
zfs_load="YES"

 /etc/rc.conf contents: 

zfs_enable="YES"
kld_list="linux linux64 cuse fusefs /boot/modules/i915kms.ko"
linux_enable="YES"
ntpd_enable="YES"
ntpd_sync_on_start="YES"
devfs_enable="YES"
devfs_system_ruleset="devfsrules_common"
dbus_enable="YES"
lightdm_enable="YES"
webcamd_enable="YES"
cupsd_enable="YES"
avahi_daemon_enable="YES"
avahi_dnsconfd_enable="YES"
moused_enable="YES"
ipfw_enable="YES"
firewall_enable="YES"
ifconfig_em0="DHCP"
wlans_iwm0="wlan0"
ifconfig_wlan0="WPA DHCP"
keymap="us.kbd"
hostname="laptop1"
radarr_enable="TRUE"
prowlarr_enable="TRUE"
lidarr_enable="TRUE"

 /etc/wpa_supplicant.conf contents: 

network={
 ssid="WakkaWakka"
 key_mgmt=WPA-PSK
 proto=RSN
 psk="Not4u2NO"
}

network={
 ssid="WakkaWakka-5G"
 key_mgmt=WPA-PSK
 proto=RSN
 psk="Not4u2NO"
}
 create your device with command:
 ifconfig wlan0 create wlandev rtwn0
 or using -HT option 

ifconfig -HT wlan0 create wlandev rtwn0

  Substitute <your device name> in place of rtwn0

Is the firmware file for your wifi device available in this file directory ?xxxx? and did it get loaded into your wifi device?
 
 Did you acknowledge the legal Copyright Notice in /boot/loader.conf file.

RealTek RTL8188CE Wii-Fi PCI network hardware setup - GhostBSD Forums post  https://forums.ghostbsd.org/viewtopic.php?f=64&t=570 

add these 10 lines to  /boot/loader.conf file 

boot_verbose="YES" 

# verbose_loading="YES"

kld_list="geom_mirror geom_journal geom_eli linux if_rtwn_pci if_rtwn"

#add if_rtwn if_rtwn_pci kernel drivers to kld_list

#if_wlan_load="YES"

if_rtwn_pci_load="YES"

if_rtwn_load="YES"

rtwn-rtl8192cfwE_B_load="YES"

rtwn-rtl8192cfwE_load="YES"

legal.realtek.license_ack=1

/etc/rc.conf add 2 lines for RTL8188CE
wlans_rtwn0="wlan0"
ifconfig_wlan0="WPA SYNC DHCP"

/etc/wpa_supplicant.conf add these 5 lines for RTL8188CE PCI wifi device 

#/etc/wpa_supplicant.conf example file for an Open Network connection to Wireless SSID name innflux 

network={
ssid=innflux
key_mgmt=NONE
}

Manually issue the wpa_supplicant CLI command with the background Dameon option and dhclient commands

killall dhclient
wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf
dhclient wlan0

For Debugging,  Use the following line for testing with the Debug and Password debug printout options
killall dhclient
service netif restart
service routing restart
wpa_supplicant -d -K -i wlan0 -c /etc/wpa_supplicant.conf
dhclient wlan0

Problems running dhclient? Then kill the previously running dhclient.

killall dhclient

dhclient wlan0

use Netstat commands to list out the new network interface connections
use Sockstat commands to list out the socket connections

netstat -r
or

netstat -i
or

sockstat -4

netstart -r

Routing tables

Internet:
Destination        Gateway            Flags     Netif Expire
default            192.168.0.1        UGS         em0
localhost          link#2             UHS         lo0
192.168.0.0/24     link#1             U           em0
192.168.0.11       link#3             UHS         lo0
192.168.0.17       link#1             UHS         lo0

Internet6:
Destination        Gateway            Flags     Netif Expire
::/96              localhost          UGRS        lo0
localhost          link#2             UHS         lo0
::ffff:0.0.0.0/96  localhost          UGRS        lo0
fe80::/10          localhost          UGRS        lo0
fe80::%lo0/64      link#2             U           lo0
fe80::1%lo0        link#2             UHS         lo0
ff02::/16          localhost          UGRS        lo0

netstart -i

Name     Mtu Network       Address              Ipkts Ierrs Idrop    Opkts Oerrs  Coll
em0     1500 <Link#1>      54:e1:ad:9f:85:4e 164479674    23     0 74960162     0     0
em0        - 192.168.0.0/2 192.168.0.17      39201131     -     - 18271599     -     -
lo0    16384 <Link#2>      lo0                 118247     0     0   118041     0     0
lo0        - localhost     localhost            84518     -     -    84518     -     -
lo0        - fe80::%lo0/64 fe80::1%lo0              0     -     -        0     -     -
lo0        - your-net      localhost            33523     -     -    33523     -     -
wlan0*  1500 <Link#3>      bc:a8:a6:d0:88:d8     4146     0     0     4199  2522     0
wlan0*     - 192.168.0.0/2 192.168.0.11          4081     -     -     6713     -     -

sockstat -4

USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS      
mike     telegram-d 36979 38 tcp4   192.168.0.17:53712    149.154.175.50:443
mike     telegram-d 36979 41 tcp4   192.168.0.17:53713    149.154.167.51:443
mike     telegram-d 36979 47 tcp4   192.168.0.17:53872    149.154.175.53:443
mike     gvfsd-smb- 2813  9  tcp4   192.168.0.17:21469    192.168.0.10:139
mike     chrome     2381  23 tcp4   192.168.0.17:42167    192.168.0.13:60000
mike     chrome     2381  25 udp4   192.168.0.17:41823    172.217.14.170:443
mike     chrome     2381  27 tcp4   192.168.0.17:53854    23.208.132.114:443
mike     chrome     2381  31 tcp4   192.168.0.17:41690    35.188.180.52:443
mike     chrome     2381  158 udp4  224.0.0.251:5353      *:*
mike     chrome     2378  176 udp4  224.0.0.251:5353      *:*
mike     transmissi 1777  13 udp4   *:63229               *:*
mike     transmissi 1777  14 udp4   *:59413               *:*
mike     transmissi 1777  15 udp4   *:44266               *:*
mike     transmissi 1777  16 tcp4   *:9091                *:*
mike     transmissi 1777  17 tcp4   *:51413               *:*
mike     transmissi 1777  19 udp4   *:51413               *:*
mike     transmissi 1777  23 udp4   192.168.0.11:12640    192.168.0.1:5351
mike     transmissi 1777  25 tcp4   192.168.0.17:60156    202.153.218.117:21
mike     transmissi 1777  28 tcp4   192.168.0.17:60183    45.154.253.8:80
mike     transmissi 1777  29 tcp4   192.168.0.17:60188    45.154.253.8:80
mike     transmissi 1777  41 tcp4   192.168.0.17:11095    37.48.95.50:49036
mike     transmissi 1777  43 tcp4   192.168.0.17:21718    213.152.161.149:49244
mike     transmissi 1777  51 tcp4   192.168.0.17:38215    95.181.233.24:32027
mike     transmissi 1777  52 tcp4   192.168.0.17:22172    121.45.160.118:51413
mike     transmissi 1777  62 tcp4   192.168.0.17:60166    45.154.253.9:80
mike     transmissi 1777  66 tcp4   192.168.0.17:11132    146.70.126.189:61314
mike     transmissi 1777  68 tcp4   192.168.0.17:39273    191.101.31.42:58899
mike     transmissi 1777  76 tcp4   192.168.0.17:41042    185.149.90.120:51055
mike     transmissi 1777  77 tcp4   192.168.0.17:56282    146.70.126.189:61314
mike     transmissi 1777  78 tcp4   192.168.0.17:41043    46.246.3.203:41974
mike     transmissi 1777  79 tcp4   192.168.0.17:41224    185.203.56.40:58427
mike     transmissi 1777  80 tcp4   192.168.0.17:41044    37.48.95.50:47511
mike     transmissi 1777  83 tcp4   192.168.0.17:55217    91.170.40.209:1503
mike     transmissi 1777  84 tcp4   192.168.0.17:42464    89.46.62.34:55945
mike     transmissi 1777  85 tcp4   192.168.0.17:31579    213.152.161.149:49244
mike     transmissi 1777  87 tcp4   192.168.0.17:41047    185.149.90.94:51522
mike     transmissi 1777  90 tcp4   192.168.0.17:41247    185.21.217.76:51086
radarr   Radarr     1547  326 tcp46 *:7878                *:*
prowlarr Prowlarr   1536  326 tcp46 *:9696                *:*
lidarr   Lidarr     1522  340 tcp46 *:8686                *:*
root     cupsd      1487  7  tcp4   127.0.0.1:631         *:*
avahi    avahi-daem 1478  14 udp4   *:5353                *:*
avahi    avahi-daem 1478  16 udp4   *:60224               *:*
ntpd     ntpd       1432  21 udp4   *:123                 *:*
ntpd     ntpd       1432  22 udp4   192.168.0.17:123      *:*
ntpd     ntpd       1432  25 udp4   127.0.0.1:123         *:*
root     syslogd    1379  7  udp4   *:514                 *:*
root     wpa_suppli 351   3  udp4   *:*                   *:*
?        ?          ?     ?  tcp4   192.168.0.17:59967    172.64.142.19:443
?        ?          ?     ?  tcp4   127.0.0.1:9696        127.0.0.1:60072
?        ?          ?     ?  tcp4   127.0.0.1:60074       127.0.0.1:9696
?        ?          ?     ?  tcp4   127.0.0.1:9696        127.0.0.1:60075
?        ?          ?     ?  tcp4   127.0.0.1:60076       127.0.0.1:9696
?        ?          ?     ?  tcp4   127.0.0.1:9091        127.0.0.1:60144
?        ?          ?     ?  tcp4   127.0.0.1:9091        127.0.0.1:60145
?        ?          ?     ?  tcp4   127.0.0.1:60075       127.0.0.1:9696
?        ?          ?     ?  tcp4   192.168.0.17:53739    202.153.218.117:21
?        ?          ?     ?  tcp4   192.168.0.17:53641    211.22.29.93:80

Check connectivity with ping command to a specific IP address like Google Domain Name service
Ping Google Domain Naming Service (DNS) 3 times.

ping -c 3 8.8.8.8

Ping Open Domain Naming Service (DNS) 3 times.

ping -c 3 208.67.222.222

Ping Hurricane Electric Internet Service Provider 3 times.

ping -c 3 he.net

Ping an OpenNic DNS server in Colorado ns4.co.us.dns.opennic.glue https://servers.opennicproject.org/
ping -c 3 63.231.92.27

#Sometimes you might need to restart the network interfaces and the routing services, after editing the /etc/rc.conf file or the /etc/wpa_supplicant.conf file.

service netif restart  && service routing restart

Ping Google Domain Naming Service (DNS) 3 times.

PING 8.8.4.4 (8.8.4.4): 56 data bytes
64 bytes from 8.8.4.4: icmp_seq=0 ttl=118 time=25.361 ms
64 bytes from 8.8.4.4: icmp_seq=1 ttl=118 time=21.035 ms
64 bytes from 8.8.4.4: icmp_seq=2 ttl=118 time=25.846 ms

--- 8.8.4.4 ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 21.035/24.081/25.846/2.163 ms

Ping Open Domain Naming Service (DNS) 3 times.

PING 208.67.222.222 (208.67.222.222): 56 data bytes
64 bytes from 208.67.222.222: icmp_seq=0 ttl=57 time=24.468 ms
64 bytes from 208.67.222.222: icmp_seq=1 ttl=57 time=31.130 ms
64 bytes from 208.67.222.222: icmp_seq=2 ttl=57 time=26.509 ms

--- 208.67.222.222 ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 24.468/27.369/31.130/2.787 ms

Ping Hurricane Electric Internet Service Provider 3 times.

PING he.net (216.218.236.2): 56 data bytes
64 bytes from 216.218.236.2: icmp_seq=0 ttl=57 time=55.286 ms
64 bytes from 216.218.236.2: icmp_seq=1 ttl=57 time=54.326 ms
64 bytes from 216.218.236.2: icmp_seq=2 ttl=57 time=58.831 ms

--- he.net ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 54.326/56.148/58.831/1.937 ms

Ping an OpenNic DNS server in Colorado ns4.co.us.dns.opennic.glue 

PING 63.231.92.27 (63.231.92.27): 56 data bytes
64 bytes from 63.231.92.27: icmp_seq=0 ttl=54 time=38.089 ms
64 bytes from 63.231.92.27: icmp_seq=1 ttl=54 time=35.111 ms
64 bytes from 63.231.92.27: icmp_seq=2 ttl=54 time=36.258 ms

--- 63.231.92.27 ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 35.111/36.486/38.089/1.227 ms
GhostBSD Telegram group https://t.me/GhostBSD or IRC chat group can help your WIFI GO, 
if you post a copy of these commands output into a pastebin.com post and

 you share the URL link for them to view this information.

root@laptop1:/home/mike/Scripts # 

root@laptop1:/etc # pciconf -lv | grep -A1 -B3 network
em0@pci0:0:31:6:	class=0x020000 rev=0x21 hdr=0x00 vendor=0x8086 device=0x15d8 subvendor=0x17aa subdevice=0x505f
    vendor     = 'Intel Corporation'
    device     = 'Ethernet Connection (4) I219-V'
    class      = network
    subclass   = ethernet
--
iwm0@pci0:5:0:0:	class=0x028000 rev=0x78 hdr=0x00 vendor=0x8086 device=0x24fd subvendor=0x8086 subdevice=0x1010
    vendor     = 'Intel Corporation'
    device     = 'Wireless 8265 / 8275'
    class      = network
root@laptop1:/etc # ghostbsd version
ghostbsd: Command not found.
root@laptop1:/etc # ghostbsd-version
22.11.22
root@laptop1:/etc # 
root@laptop1:/etc #

**Comment by ericbsd** [comment]
Wifi performance is a FreeBSD issue. GhostBSD does not deal with this kind of issue. 

FreeBSD does not support N AC and AX. It would be better to make a ticket for FreeBSD than GhostBSD.
