### ISSUE TITLE
20.10.31-KDE install new filesystem out of space

### ISSUE THREAD

**Issue by libseide** [ghostbsd/ghostbsd-src#26]
![VirtualBox_FBSD_01_11_2020_13_37_44](https://user-images.githubusercontent.com/73787040/97806384-a45b9880-1c5b-11eb-9855-624df0a6f842.png)

**Comment by ericbsd** [comment]
KDE is kinda out of the scope of the project there is no one working on that version.

**Comment by vimanuelt** [comment]
The KDE ISO file is 3.8 GiB in size. Increasing the memory requirement to 6GiB or 8GiB for KDE (Plasma) is advised.

**Comment by grahamperrin** [comment]
> The KDE ISO file is 3.8 GiB in size. Increasing the memory requirement to 6GiB or 8GiB for KDE (Plasma) is advised.

With `GhostBSD-20.12.21-KDE.iso` at `4.2` GiB: 8,192 MB memory is not a workaround. 

### `4,096` MB memory

Reportedly out of space after reading `2.97` GB from disk: 

![2021-05-04 06:37:52](https://user-images.githubusercontent.com/192271/116967595-93dbb780-acaa-11eb-8032-7e79f242be10.png)

### `5,120` MB memory

Again, reportedly out of space after reading `2.97` GB from disk: 

![2021-05-04 06:42:36](https://user-images.githubusercontent.com/192271/116967655-ba015780-acaa-11eb-94b5-067fa3faa14a.png)

Again, reportedly out of space after reading `2.97` GB from disk: 

https://user-images.githubusercontent.com/192271/116967724-e5844200-acaa-11eb-858c-4d372824ff5e.mp4

### `5,120` MB memory

`2.96` GB read from disk: 

![2021-05-04 07:18:00](https://user-images.githubusercontent.com/192271/116967818-19f7fe00-acab-11eb-9ee2-7fec443bd546.png)

… then again, reportedly out of space after reading `2.97` GB from disk: 

![2021-05-04 07:18:20](https://user-images.githubusercontent.com/192271/116967885-34ca7280-acab-11eb-92a5-6afc2dbc768f.png)

![2021-05-04 07:19:09](https://user-images.githubusercontent.com/192271/116967895-38f69000-acab-11eb-9b8c-e05790294535.png)

**Comment by grahamperrin** [comment]
https://github.com/ghostbsd/ghostbsd-src/issues/26#issuecomment-742931918

> KDE is kinda out of the scope of the project there is no one working on that version.

Understood and agreed. 

Still, eventually, it might be nice to understand and work around situations such as this. I'm not convinced that increasing the available memory is a workaround …

### `10,000` MB memory

Again, reportedly out of space after reading `2.97` GB from disk: 

https://user-images.githubusercontent.com/192271/116975831-20d93d80-acb8-11eb-8e4c-e11583e169ce.mp4

**Comment by ericbsd** [comment]
It is a close ticket if people want KDE they can install it with `sudo pkg install kde5`.

I not sure if we will have a functional KDE ISO. Just managing MATE and the OS is a lot to do.

**Comment by grahamperrin** [comment]
Sure. No expectation of the GhostBSD project providing (and maintaining) a distribution to include KDE. 

For me, here, the memory aspect is of interest …

----

… KDE aside, please: 

* what exactly motivates the suggestion to have 6 GB for the `.iso` with MATE?

https://github.com/ghostbsd/ghostbsd.org/issues/4
