### ISSUE TITLE
[Feature] Update to yt-dlp

### ISSUE THREAD

**Issue by tim-pearce** [ghostbsd/ghostbsd-src#267]
### Describe the feature or enhancement

The current version of yt-dlp no longer works with youtube.
It has been update upstream so that it does work. There is a linux Appimage.
Could the GhostBSD version be updated please?
Is there a process for ensuring that programs like this which may need to change 'suddenly' can be kept up to date?

### Why this request?

I use this program at least once a week. Currently I have to run it in Linux.

**Comment by ericbsd** [comment]
I sent the new build of packages this morning. You should have the newest yt-dlp.
