### ISSUE TITLE
[BUG] nextcloudclient missing and uninstalled

### ISSUE THREAD

**Issue by tim-pearce** [ghostbsd/ghostbsd-src#269]
### Version

23.02.02

### Explain the issue and what happens

nextcloudclient is no longer available. What's more it gets uninstalled by update-station.

I noticed previously on one of my PCs that it was no longer available. I tried to reinstall from ports but that failed. I subsequently reinstalled version 3.6.1 from the cached copy. 

### Explain how to reproduce the bug?

Do an update.

### What is the Expected behavior (if applicable)

Should update, or at least not delete what I already had.

### Additional context (if applicable)

I am updating two PCs now and reinstall nextcloudclient on them first before doing the update on this PC.

**Comment by ericbsd** [comment]
[deskutils/nextcloudclient](https://www.freshports.org/deskutils/nextcloudclient/) depend on python27-2.7.18_2 it failed at the patch level http://builder2.ghostbsd.org/data/ghostbsd-13-ghostbsd-ports/2023-03-15_07h31m42s/logs/errors/python27-2.7.18_2.log

I will try to fix that soon.

**Comment by tim-pearce** [comment]
It uses qt5-webengine which tries to use the earlier version of libvpx. Tried to delete and replace libvpx with the earlier version but that would delete a bunch of applications.
Have reverted my laptop to the backup environment from before the update. Won't update this PC because I really need nextcloudclient.
BTW there is a later version of nextcloudclient than 3.6.1
Thanks for your hard work.

**Comment by ericbsd** [comment]
After removing this file https://github.com/ghostbsd/ghostbsd-ports/commit/33d404e7aea882cc5aa5d2a44e86cb9bdaf7e54a, python27 started to build on my local system.

I started a build to see if nextcloudclient will build this time.

**Comment by ericbsd** [comment]
The latest version to be built is 3.6.6.

**Comment by ericbsd** [comment]
python27 did build, so we should be good to have nextcloudclient  3.6.6 built.
![image](https://user-images.githubusercontent.com/4249848/225891297-07a1e661-9f9d-4c6f-885e-cde8cc1b635a.png)
