### ISSUE TITLE
GhostBSD Installer wifimgr doesn't set up AX200 

### ISSUE THREAD

**Issue by nevillehay** [ghostbsd/ghostbsd-src#276]
### Version

23.03.17

### Explain the issue and what happens

AX200 wifi doesn't get set up by wifimgr properly. When the desktop appears, and I click on the wifimgr the only option is to "Close network Manager". The tooltip says "Network card is not enabled". The /etc/rc.conf entries for netwotk are 

ifconfig_re0="DHCP"
ifconfig_iwlwifi0="DHCP"

the entries should be

wlans_iwlwifi0="wlan0"
ifconfig_wlan0="WPA DHCP"

### Explain how to reproduce the bug?

Boot GhostBSD install media with computer with AX200 wifi

/etc/rc.conf should contain

wlans_iwlwifi0="wlan0"
ifconfig_wlan0="WPA DHCP"

### What is the Expected behavior (if applicable)

Router should be discovered and wifi should be connected.

**Comment by ericbsd** [comment]
It is a simple fix ghostbsd/ghostbsd-src#276.

**Comment by ericbsd** [comment]
This should be fixed on the last iso.
