### ISSUE TITLE
[BUG] OBS-studio has disappeared from the repository

### ISSUE THREAD

**Issue by tim-pearce** [ghostbsd/ghostbsd-src#283]
### Version

23.04.15

### Explain the issue and what happens

I few days ago I was able to install obs-studio on my laptop but now it does not appear when I do a pkg search.

### Explain how to reproduce the bug?

Upgrade to this version of GhostBSD.

### What is the Expected behavior (if applicable)

That obs-studio would continue to be available.

### Additional context (if applicable)

It's working fine on the laptop for my purposes except that it won't close. I have to kill it.

I copied the .pkg files over to this PC and managed to get it to install but when I run it it tells me it can't use my GPU, probably because it's too old. That's a pain because this PC has two monitors which would have been more convenient.
In stalled on my Linux laptop and it didn't like that GPU either!

**Comment by ericbsd** [comment]
Sorry, for the long wait obs-studio should now be available.

I had to make a rebuild to fix the issue.
