### ISSUE TITLE
GhostBSD repository certificate expired 4/18/23 11:16AM[BUG] <title>

### ISSUE THREAD

**Issue by Pharmerdon3855** [ghostbsd/ghostbsd-src#284]
### Version

23.04.02

### Explain the issue and what happens

[Hello...I'm unable to update or add software using Software Station or Upgrade station. When I "google" [pkg.ghostbsd.org](https://pkg.ghostbsd.org/) I get a message: This server could not prove that it is pkg.ghostbsd.org*; its security certificate expired in the last day. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Tuesday, April 18, 2023. Does that look right? If not, you should correct your system's clock and then refresh this page....*How do I let them know?

### Explain how to reproduce the bug?

attempt to update using Update Station

### What is the Expected behavior (if applicable)

update

**Comment by ericbsd** [comment]
Thanks, I just renewed it.

**Comment by Pharmerdon3855** [comment]
Thank you!!!
    On Tuesday, April 18, 2023 at 06:29:03 PM GMT-5, Eric Turgeon ***@***.***> wrote:  
 
 


Thanks, I just renewed it.
