### ISSUE TITLE
[Epic] Add a BE manager UI to create backup and activate BE

### ISSUE THREAD

**Issue by ericbsd** [ghostbsd/ghostbsd-src#32]

**Comment by grahamperrin** [comment]
Food for thought: 

## SysAdm: Boot Environment Manager

![image](https://user-images.githubusercontent.com/192271/116773158-aefcbc00-aa4b-11eb-9400-3527e9cd4e62.png)

– from part of a screenshot at https://distrowatch.com/weekly.php?issue=20170501#trueos

From [3+ months on TrueOS – a critical write-up | eerielinux](https://eerielinux.wordpress.com/2016/12/20/3-months-on-trueos-a-critical-write-up/) (2016-12-20): 

> **Good: SysAdm**
> 
> This is one aspect where TrueOS really shines. … middleware that exposes an API to manage FreeBSD based machines locally or remotely.
> 
![image](https://user-images.githubusercontent.com/192271/116773591-0dc33500-aa4e-11eb-8d28-94f0a855aade.png)
> 
> _The ‘SysAdm’ client for the local machine_
> 
> … the local client comes with a very nice GUI that has a lot of functionality …

From [SysAdm:FreeBSD Administration Made Easy](https://www.socallinuxexpo.org/sites/default/files/presentations/2017_SCALE_SysAdm.pdf) (2017-03-05), with added emphasis: 

> SysAdm Client
> 
> * Graphical client written purely in Qt5
> * Fully **cross-platform** …

### Archived/historical

* https://github.com/trueos/sysadm
* https://github.com/trueos/sysadm-docs
* https://www.freshports.org/sysutils/sysadm/

In the Wayback Machine, however this is without images: https://web.archive.org/web/20180929002502/https://sysadm.us/handbook/client/sysadmclient.html#boot-environment-manager

There's a copy of older (PC-BSD) guidance at https://ftp.icm.edu.pl/packages/pcbsd/iso/11.0-CURRENTJUNE2016/amd64/docs/html/sysadmclient.html#boot-environment-manager – this, too, lacks images.

**Comment by ericbsd** [comment]
It is unmaintained and written in QT.

**Comment by grahamperrin** [comment]
Thank you, I understand (from the code being archived) that it is unmaintained, I wondered whether _reusing_ parts of the code might be more efficient than creating something new. 

If not new, did you have in mind an existing application/UI?

I had no idea that Qt5 was an issue, sorry.

**Comment by ericbsd** [comment]
I have a python module that I maintain for bectl, which will be the module I will use.

https://github.com/ghostbsd/pybectl

I wouldn't say I like QT, and not a lot of people know that.

**Comment by mfjurbala** [comment]
I'm planning on working on this. I'm in the process of learning some GTK basics in order to make the GUI. The GUI will be located in [Backup-station](https://github.com/ghostbsd/backup-station) and the python bectl module is in [pybectl](https://github.com/ghostbsd/pybectl)

**Comment by mfjurbala** [comment]
@ericbsd, I have most of the basic functionality done but I want to clean up a few things that I know could be better. I also have a few questions.

1. How should I include pybectl? Should I copy that file into this repo or is there a better way to make sure that module is present on the system?
3. I haven't developed anything before so this will likely need some heavy refactoring. Do you want me to make a PR with what I have or is there a certain way you want to go about that?
4. I copied the class and methods from software-station that ask for a user password on start. Should I write my own implementation from scratch or is that reuse okay?

**Comment by ericbsd** [comment]
@mfjurbala sorry for the wait.

1. pybectl is a package that comes already installed on GhostBSD. It is built from a port I made at https://github.com/ghostbsd/ghostbsd-ports.
2. You can make a PR I will review and help you improve it if needed.
3. The reuse is OK.

**Comment by mfjurbala** [comment]
No problem, thanks for the help. I thought I'd have this done sooner but things keep coming up. I'll get something eventually.

**Comment by ericbsd** [comment]
> No problem, thanks for the help. I thought I'd have this done sooner but things keep coming up. I'll get something eventually.

No worries, life always get in the of a free open source project. Myself I am not able to put the time I would like.

**Comment by ericbsd** [comment]
Completed!

Thanks again @mfjurbala

**Comment by mfjurbala** [comment]
No problem, hopefully I can help out more. Just a matter of finding time.
