### ISSUE TITLE
Some applications do not follow the system theme

### ISSUE THREAD

**Issue by spanakop** [ghostbsd/ghostbsd-src#37]
The following applications are still using the default window border theme, the three coloured circles, that came on a fresh install of GhostBSD (21.01.20)
'Color Profile Viewer'
'dconf Editor'
'Glade'
'Password and Keys'

I am using a mix of other themes for the general theme, icons and window border.
![Screenshot at 2021-02-08 09-54-12](https://user-images.githubusercontent.com/7239106/107204318-70c7a180-69f4-11eb-9c63-777bd9ad8bdf.png)

**Comment by ericbsd** [comment]
cant reproduce in 21.05.01

**Comment by spanakop** [comment]
Apologies for the late reply, I have only just installed the latest version. I will keep an eye on this as I now have the latest version of GBSD installed (GhostBSD-21.05.04.iso)

**Comment by spanakop** [comment]
I am still seeing these problems with these apps on the latest version.

'dconf Editor'
'Glade'
'Password and Keys'

'Color Profile Viewer' is not installed, so i can't test it

**Comment by ericbsd** [comment]
They are behaving like expected on all my systems.
![image](https://user-images.githubusercontent.com/4249848/117540679-a295d780-afe6-11eb-9586-6f00a7820537.png)

**Comment by spanakop** [comment]
Hi, but you're still using the default window border theme. If you change it to something else other than the three circle colours from Vimix, you will see the problem.

Sorry, I should have been more explicit in my original description.

**Comment by ericbsd** [comment]
Mate border themes are not compatible with Gnome borders. The default them of GhostBSD supports Mate, Gnome, Cinnamon, and XFCE. By selecting a MATE border, it changes only borders controlled by MATE. Gnome app will follow the default theme, not the Marco interface.

**Comment by spanakop** [comment]
Ok thank you. I was not aware of this
