### ISSUE TITLE
Changes to start-up applications are not always saved

### ISSUE THREAD

**Issue by spanakop** [ghostbsd/ghostbsd-src#40]
If I add a custom startup entry via the Startup Preferences dialogue, it will work ok upon logging out and back in again. But if I then go back and edit the command field entry, the changes made are not saved to the desktop file in ~/.config/autostart/ sometimes, I need to edit the desktop file to make the change last across a new session.

I am using Mate as my desktop.

**Comment by ericbsd** [comment]
Can't reproduce on 21.05.01

**Comment by spanakop** [comment]
Apologies for the late reply, I have only just installed the latest version. I will keep an eye on this as I now have the latest version of GBSD installed (GhostBSD-21.05.04.iso)
