### ISSUE TITLE
input/output error with aircrack-ng port 

### ISSUE THREAD

**Issue by blindone0** [ghostbsd/ghostbsd-src#48]
hello please help me. I want to compile aircrack-ng couse pkg port seems to be broken.
besside-ng: wi_write(): input/output error :: on runtime 
where i can report about bug? And what is the right way to do it? Is there some dumps need to be attached?
I don't even dream to compile it by myself

**Comment by ericbsd** [comment]
For help, reach GhostBSD Forum or GHostBSD Telegram.

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues
