### ISSUE TITLE
[BUG] GhostBSD-13-21.04.16 ISO doesn't boot in Ventoy 1.0.40

### ISSUE THREAD

**Issue by ThePowerOfDreams** [ghostbsd/ghostbsd-src#50]
**Describe the bug**
GhostBSD-13-21.04.16.iso doesn't finish booting when bootstrapped from a flash drive with [Ventoy 1.0.40](https://www.ventoy.net/en/index.html).

**To Reproduce**
1. Install Ventoy 1.0.40 on a flash drive
2. Copy GhostBSD-13-21.04.16.iso to the large partition on that flash drive
3. Boot the machine from that flash drive and choose GhostBSD-13-21.04.16.iso

**Expected behavior**
It boots to a desktop

**Actual behavior**
System displays the following then makes no further progress:
> ==> Remount rootfs as read-write
> ==> Make mountpoints /cdrom
> Waiting for GhostBSD media to initialize

**Additional context**
GhostBSD-21.01.20.iso boots fine under Ventoy 1.0.40, as does FreeBSD-13.0-RELEASE-amd64-dvd1.iso

**Comment by ThePowerOfDreams** [comment]
This issue also affects GhostBSD-13-21.04.16.iso.

**Comment by OskarKarpinski** [comment]
Ventoy 1.0.41
3. Add support for new GhostBSD release.
https://github.com/ventoy/Ventoy/releases/tag/v1.0.41

**Comment by ericbsd** [comment]
> Ventoy 1.0.41
> 3. Add support for new GhostBSD release.
> 7. New image support: GhostBSD-13-21.04.16.iso (Legacy + UEFI)
> https://github.com/ventoy/Ventoy/releases/tag/v1.0.41

Thanks @OskarKarpinski

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues
