### ISSUE TITLE
cd0 ejected from the desktop, remains on the desktop

### ISSUE THREAD

**Issue by grahamperrin** [ghostbsd/ghostbsd-src#58]
Bug report in this repository required by the template for https://github.com/mate-desktop/caja/issues/1522

**Comment by ericbsd** [comment]
It is not really a bug from MATE because we don't use gvfs with libudisks.
But if they could fix that would be huge for us.

**Comment by grahamperrin** [comment]
Thank you. 

Do you know, is there a comparable symptom with real hardware, or is this limited to the VirtualBox environment?

**Comment by ericbsd** [comment]
I have seen similar on hardware.

**Comment by ericbsd** [comment]
Same here. If it is a bug, it should have an [BUG] in the title

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues
