### ISSUE TITLE
Add 'Fortune' app back into repo

### ISSUE THREAD

**Issue by spanakop** [ghostbsd/ghostbsd-src#65]
Currently, you have the fortune-mod files available for download, but the main fortune app is missing and not available for download, so these cannot be used.

Can you please add the main fortune app back into the repo so these mod files can be used.

**Comment by ericbsd** [comment]
This issue is not following the templet

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues
