### ISSUE TITLE
[BUG] 'Open as Administrator' command not working in Caja

### ISSUE THREAD

**Issue by spanakop** [ghostbsd/ghostbsd-src#66]
When I right click on a file in Caja and select "Open as administrator", nothing happens. I'm expecting to be asked for my password and the document opened or command executed as if I had wheel/operator/root privileges

This is a really useful command to have available on the desktop when I don't want to work in the CLI environment.

**Comment by ericbsd** [comment]
Not following the templet. Sorry, but I made that template for a reason.

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues
