### ISSUE TITLE
[Feature] Please add the 'Fortune' app into the repo

### ISSUE THREAD

**Issue by spanakop** [ghostbsd/ghostbsd-src#68]
**Is your feature request related to a problem? Please describe.**
Currently, you have the fortune-mod files available for download, but the main fortune app is missing and not available for download, so these files cannot be used.

**Describe the solution you'd like**
Could the main fortune app that uses these mod files be put back into the GBSD repo please

**Additional context**
If the fortune app is not going to be added, then the associated mod files also need removing. There is a ruby gem fortune file, but I do not think this is the correct fortune application.

**Comment by ericbsd** [comment]
In the latest version of GhostBSD fortune is installed.

```
> fortune
No fortunes found in /usr/share/games/fortune:/usr/local/share/games/fortune.
```

But the default freebsd fortunes was removed from the base and put into a packages name **fortune-mod-freebsd-classic**.

**Comment by spanakop** [comment]
I have received an update today and it is now showing up. I have installed fortune-mod-freebsd-classic. I'm pretty sure this was not present when I raised the ticket, perhaps I was mistaken, as I was looking for just fortune not the version installed now. 

Anyway, thank you

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues
