### ISSUE TITLE
[BUG] <-   telegram-desktop crashing when you send the voice message in chat

### ISSUE THREAD

**Issue by www19701** [ghostbsd/ghostbsd-src#71]
Has anyone got crashing telegram-desktop while voice chatting? I have it happening constantly after updates, that happens in desktop version.

![Screenshot at 2021-05-13 22-45-43](https://user-images.githubusercontent.com/46078643/118218870-f288fa00-b43d-11eb-831c-621b0ea9ffd6.png)

**Comment by ericbsd** [comment]
Templet explicitly says that every ticket with a question will be close.

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues
