### ISSUE TITLE
shutdown -h now Does not shutdown properly

### ISSUE THREAD

**Issue by thedaemon** [ghostbsd/ghostbsd-src#73]
type:

>doas shutdown -h now

It will get stuck shutting down and stay active forever. It starts the shutdown process but doesn't finish it. The work around is to use >poweroff instead.

**Comment by ericbsd** [comment]
On GhostBSD -h does not power off the system it only halts it. -p is to use to halts and the power of the system.

**Comment by ericbsd** [comment]
Also, this ticket does not follow the temple so I have to close it.

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues
