### ISSUE TITLE
[Feature] Missing packages in the pkg repo

### ISSUE THREAD

**Issue by whit3rav3n** [ghostbsd/ghostbsd-src#74]
i miss many packages in the pkg repo of ghostbsd which are available in freebsd.
mupdf for example. will these packages be added later or do i have to build them myself ?
Are there other repos i can use ?

**Comment by ericbsd** [comment]
No question on tickets. Next time read the template.

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues
