### ISSUE TITLE
[Feature] Add GhostBSD to uname output so pfetch/neofetch can display correct OS info

### ISSUE THREAD

**Issue by spanakop** [ghostbsd/ghostbsd-src#75]
**Is your feature request related to a problem? Please describe.**
When you run a program like pfetch, neoftech etc or even uname, you get FreeBSD back as the OS. It would be nice if it was possible to show that it is a FreeBSD variant called GhostBSD.

**Describe the solution you'd like**
Programs like pfetch, neoftech or uname, display GhostBSD.

**Additional context**
Would increase visibility of GhostBSD usage. Not in your scope, but it requires programs like pftech neoftech etc, to be changed to reflect ascii art of GhostBSD

**Comment by ericbsd** [comment]
Uname on  Linux will display Linux, not the distro name. In most cases,/etc/os-release looks to be the file that is in use for this.

This Ticket #141 looks to solve the problem for this.

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues
