### ISSUE TITLE
[BUG] /etc/init.d/bthidd does not use evdev flags, preventing bluetooth keyboards from typing

### ISSUE THREAD

**Issue by amshafer** [ghostbsd/ghostbsd-src#76]
**Describe the bug**
On FreeBSD, `/etc/rc.d/bthidd` checks if evdev is enabled in the kernel, and adds the `-u` flag to bthidd. This hooks whatever keyboard bthidd connects into evdev, and it all works fine.

GhostBSD's bthidd service does not check if evdev is enabled, and has no logic for adding the `-u` argument. When setting up my bluetooth keyboard (Keychron K2), this prevented it from giving any input. The keyboard would connect, `/dev/kbd4` would be created, but I couldn't type. Adding `-u` fixed things and lets me type this bug report.

**To Reproduce**
1. have evdev in your kernel
2. connect a bluetooth keyboard (aka bluetooth-config and start the services)
2. you are now probably unable to type

**Expected behavior**
If a bt keyboard connects, it should be able to type.

**Additional context**

Here is my diff in this repo that fixes the problem:
```
diff --git a/libexec/rc/etc.init.d/bthidd b/libexec/rc/etc.init.d/bthidd
index cba3b333211..9d4978819b9 100644
--- a/libexec/rc/etc.init.d/bthidd
+++ b/libexec/rc/etc.init.d/bthidd
@@ -16,7 +16,7 @@ error_file="/var/log/${name}"
 
 config="${bthidd_config:-/etc/bluetooth/${name}.conf}"
 hids="${bthidd_hids:-/var/db/${name}.hids}"
-command_args="-d -c ${config} -H ${hids} -p ${pidfile}"
+command_args="-d -c ${config} -H ${hids} -p ${pidfile} -u"
 required_modules="kbdmux vkbd ng_btsocket"
 
 depend(){
```

I *think* that ghostbsd should always have evdev enabled, so I didn't do a check for the evdev kernel support. I'm not very familiar with how to do that properly since I haven't touched openrc before.

Here's the bthidd `-u` bits from the manpage:
```
     -u      Enable support for input event device protocol.  Requires evdev
             and uinput drivers to be loaded with kldload(8) or compiled into
             the kernel.
```

Is there any way we can get that flag added to the bthidd service to improve keyboard support? Thanks!

**Comment by ericbsd** [comment]
We moved back to rc.d so this is not valid anymore

**Comment by ericbsd** [comment]
issue moved from ghostbsd/ghostbsd-src to ghostbsd/issues
