### ISSUE TITLE
minor cosmetic - Authentication is spelled wrong

### ISSUE THREAD

**Issue by tecnixx** [ghostbsd/ghostbsd-src#78]
Wireless "authentication" is spelled wrong in the screen that pops up to enter the wireless password.

**Comment by ericbsd** [comment]
I am not seeing this in the new code.

**Comment by tecnixx** [comment]
Well it was after a fresh install, maybe next time I should update before saying anything. Sorry about that, first day here ^_^

Stephanie 
-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


Jun 15, 2021, 19:42 by ***@***.***:

**Comment by tecnixx** [comment]
Also,  thank you for all that you do. This distribution is really bridging the gap, I've been a FreeBSD fan for too long, between this and digital ocean; I think I can learn a lot. Also, a great daily driver. I was sad when I went to look for PCbsd and it was no longer supported so thank you for picking up where Kris Moore left off. 

Cheers, 

Stephanie
-- 
 Sent with Tutanota, the secure & ad-free mailbox:  
 https://tutanota.com


Jun 15, 2021, 19:42 by ***@***.***:

**Comment by vimanuelt** [comment]
I did not see that authentication was misspelled, but Wi-Fi was. It was "wi-Fi Authentication" instead of "Wi-Fi Authentication"

**Comment by ericbsd** [comment]
It is fixed.
