### ISSUE TITLE
Error on wakeup from Hibernation when Video Screen goes to sleep. Screen won't light back up.

### ISSUE THREAD

**Issue by wb7odyfred** [ghostbsd/ghostbsd-src#8]
I find that coming out of Hibernation, Screen backlight , won't light back up.  No GUI screen image appears. Like when you hit the enter key or the space bar or swipe on the track pad.  or Use the function
I type Ctl-Alt-F2 or Ctrl-Alt-F8 to wake up screen monitor and see the ttyX "login" prompt. Then I type Ctl-Alt-F9 and the graphic desktop window appears just as it was when I walked out of the room several minutes ago. GUI Desktop operation is good, after Ctl-Alt-F9. Fred 

ps. I was playing a youtube video when the computer went to hibernate. (sleep). When I clicked any key to wake up the process, I could hear the youtube video sound playing, but just a black screen monitor.   Until I hit Ctl-Alt-F8 [get the tty7 login prompt immediately.  Wait 4 seconds then type] Ctl-Alt-F9 to switch to GUI screen.  Immediately the GUI Screen backlight turns on and the Video is continuing to play audio sound and video motion.
Then I could see my desktop and the youtube video playing. Hope this information helps. Ready to  give more information and test what you suggest. Fred Finster
 # uname -K
1201513
 # uname -a
FreeBSD fred-ghostbsd-pc1 12.1-STABLE FreeBSD 12.1-STABLE GENERIC  amd64

# sudo pkg update
Password:
Updating GhostBSD repository catalogue...
GhostBSD repository is up to date.
All repositories are up to date.
# sudo pkg upgrade
Updating GhostBSD repository catalogue...
GhostBSD repository is up to date.
All repositories are up to date.
Checking for upgrades (0 candidates): 100%
Processing candidates (0 candidates): 100%
Checking integrity... done (0 conflicting)
Your packages are up to date.
 # date
Thu May 14 13:30:03 PDT 2020
----------------------------------------------
#HW ACPI  Listing

> root@fred-ghostbsd-pc1:/boot # sysctl hw.acpi
> hw.acpi.acline: 1
> hw.acpi.battery.info_expire: 5
> hw.acpi.battery.units: 1
> hw.acpi.battery.state: 0
> hw.acpi.battery.rate: 0
> hw.acpi.battery.time: -1
> hw.acpi.battery.life: 99
> hw.acpi.thermal.tz0._TSP: -1
> hw.acpi.thermal.tz0._TC2: -1
> hw.acpi.thermal.tz0._TC1: -1
> hw.acpi.thermal.tz0._ACx: -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
> hw.acpi.thermal.tz0._CRT: -1
> hw.acpi.thermal.tz0._HOT: -1
> hw.acpi.thermal.tz0._PSV: -1
> hw.acpi.thermal.tz0.thermal_flags: 0
> hw.acpi.thermal.tz0.passive_cooling: 0
> hw.acpi.thermal.tz0.active: -1
> hw.acpi.thermal.tz0.temperature: 44.1C
> hw.acpi.thermal.user_override: 0
> hw.acpi.thermal.polling_rate: 10
> hw.acpi.thermal.min_runtime: 0
> hw.acpi.cpu.cx_lowest: C1
> hw.acpi.reset_video: 0
> hw.acpi.handle_reboot: 1
> hw.acpi.disable_on_reboot: 0
> hw.acpi.verbose: 0
> hw.acpi.s4bios: 0
> hw.acpi.sleep_delay: 1
> hw.acpi.suspend_state: S3
> hw.acpi.standby_state: NONE
> hw.acpi.lid_switch_state: NONE
> hw.acpi.sleep_button_state: S3
> hw.acpi.power_button_state: S5
> hw.acpi.supported_sleep_state: S3 S4 S5

Googled following URLs
[https://www.freebsd.org/cgi/man.cgi?acpi_ibm](url)
on my ThinkPad T430,  I might try loading acpi_ibm module by adding line to loader.conf
`acpi_ibm_load="YES"`
 # sysctl dev.acpi
dev.acpi.0.%parent: nexus0
dev.acpi.0.%pnpinfo: 
dev.acpi.0.%location: 
dev.acpi.0.%driver: acpi
dev.acpi.0.%desc: LENOVO TP-G1
dev.acpi.%parent: 

# sysctl dev.acpi_ibm
dev.acpi_ibm.0.handlerevents: NONE
dev.acpi_ibm.0.mic_led: 0
dev.acpi_ibm.0.fan: 1
dev.acpi_ibm.0.fan_level: 0
dev.acpi_ibm.0.fan_speed: 2562
dev.acpi_ibm.0.wlan: 1
dev.acpi_ibm.0.bluetooth: 0
dev.acpi_ibm.0.thinklight: 0
dev.acpi_ibm.0.mute: 0
dev.acpi_ibm.0.volume: 0
dev.acpi_ibm.0.lcd_brightness: 0
dev.acpi_ibm.0.hotkey: 0
dev.acpi_ibm.0.eventmask: 134217723
dev.acpi_ibm.0.events: 1
dev.acpi_ibm.0.availmask: 134217723
dev.acpi_ibm.0.initialmask: 2056
dev.acpi_ibm.0.%parent: acpi0
dev.acpi_ibm.0.%pnpinfo: _HID=LEN0068 _UID=0
dev.acpi_ibm.0.%location: handle=\_SB_.PCI0.LPC_.EC__.HKEY
dev.acpi_ibm.0.%driver: acpi_ibm
dev.acpi_ibm.0.%desc: IBM ThinkPad ACPI Extras
dev.acpi_ibm.%parent: 

[https://superuser.com/questions/1246297/how-to-change-brightness-in-freebsd](url)
[https://wiki.freebsd.org/MateuszPiotrowski/Yoga314/X](url)

**Comment by ericbsd** [comment]
I do not think that hibernation is works properly on FreeBSD.

**Comment by ericbsd** [comment]
There is not much we can do to fix that on our side might worth to report that to FreeBSD
