### ISSUE TITLE
[BUG] Installer hangs at cleaning

### ISSUE THREAD

**Issue by SnowCrestGuy** [ghostbsd/ghostbsd-src#82]
**To Reproduce**

install GBSD with advance partitioning
installer accepts input and then hangs at cleanup

**Expected behavior**
complete install

The installer doesn't check for other zroot pool name (a popular name) and it installs by default the pool with that pool name. The full disk install allows user to change pool name before installing. Having same name will cause a zpool import error. I validated this by removing the offending zroot on the other disk. The install was restarted and completed normally.

**Comment by ericbsd** [comment]
@SnowCrestGuy do you have another system with ZFS on the same disk?

**Comment by ericbsd** [comment]
ping

**Comment by SnowCrestGuy** [comment]
No the freebsd loader does not allow for that.  it searches for the first freebsd kernel  with zfs file system taking priority. This was on for two disks.

Sorry for the delay I loose things in my mailbox all the time.

**Comment by ericbsd** [comment]
- [ ] Add labelclear after all partition created for zfs in pc-sysinstall like FreeBSD installer
- [ ] Add label clear for partition created by GBI
