### ISSUE TITLE
[Bug]: /bin/bash  needs linked to /usr/local/bin/bash   ln /usr/local/bin/bash /bin/bash

### ISSUE THREAD

**Issue by wb7odyfred** [ghostbsd/ghostbsd-src#84]
### Describe the bug

/bin/bash  needs linked to /usr/local/bin/bash   ln /usr/local/bin/bash /bin/bash

"/bin/bash"    does not EXSIST in GhostBSD 13.0 installation

Some script files expect to use  /bin/bash

I believe it is a simple missing hard link ( would a soft link work better?  ln -s /usr/local/bin/bash /bin/bash )

### How to reproduce the bug?

Run a shell script that is expecting to use  "/bin/bash"

### Expected behavior

I expect shell scripts to just work properly.

**Comment by ericbsd** [comment]
`/bin/bash` does not exist in GhostBSD because GhostBSD is not Linux.

We are not gonna start mixing third-party software with the base.

Proper scripting would be /usr/bin/env bash, and a script with /bin/bash was written for Linux only.

Nothing to change here.
