### ISSUE TITLE
The latest update disenabled network card. on my Dell Realteak card.[Bug]: 

### ISSUE THREAD

**Issue by chatk7** [ghostbsd/ghostbsd-src#86]
### Describe the bug

Latest update disable my Dell Realtek network card.

### How to reproduce the bug?

install those 2 updates issued last  friday.

### Expected behavior

a fix.

**Comment by ericbsd** [comment]
Not really useful information.

**Comment by ericbsd** [comment]
What ifconfig shows and what is in /etc/rc.conf?

**Comment by chatk7** [comment]
The flash drive I installed the system to has been erased. No additonal info.  I ran the Aug 30 ISO live on a Dell Inspiron laptop and it worked. But it failed to install from my Dell Vostro desptop.
