### ISSUE TITLE
won't boot

### ISSUE THREAD

**Issue by chatk7** [ghostbsd/ghostbsd-src#90]
Installed the new ISO build and it did not boot.
On the previous ISO, the updates worked in my Dell Inspiron 15 laptop but internet was hacked down to 8M from the normal 10M. And it failed the network card in my Dell Vostro desktop. Changed to a Broadcom 3471 card, it failed alltogther.
Unable to use it now.

**Comment by ericbsd** [comment]
All issues without made without the templet will be close.
