### ISSUE TITLE
[Bug]: New ISO build failed to boot.

### ISSUE THREAD

**Issue by chatk7** [ghostbsd/ghostbsd-src#91]
### Describe the bug

won't boot. But the Sep 09,2021 latest build did work on my Vostro desktop. Network was interrupted for 3 times after modem booted. My Inspirion laptop would get hacked down to 3M from the noraml 12M on my clable internet.

### How to reproduce the bug?

Tried it on those pcs.

### Expected behavior

Improved netwok managment against intrusion.

**Comment by chatk7** [comment]
/etc/rc.config was blank when it was blocked. 
It made connection after the modom rebooted.

**Comment by grahamperrin** [comment]
> `/etc/rc.config`

There's no such file. Instead: 

`/etc/rc.conf`

**Comment by ericbsd** [comment]
What the title has to do with The described bug?

**Comment by chatk7** [comment]
I mentioned the ISO as to indicate the confusion. Ths ISO failed to boot but the Latest Build did boot yet they have the same number of 21.09.08.
Then I releaized the Latest Build network works 2nd boot of modem, so I added it to the report.












 On Monday, September 13, 2021, 04:29:21 AM PDT, Eric Turgeon ***@***.***> wrote:










What the title has to do with The described bug?



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ericbsd** [comment]
The thing is, I do not understand the original issue, I need better detail, or I will close this ticket.

**Comment by chatk7** [comment]
The ISO build was installed to a flash drive successfully. But the system in the flash drive failed to boot on my Vostro 3990 desktop, 
I use the next day build and it booted. Bit it always needed the dvd sitting on the optical drive to boot. The system flash drive won't boot without the dvd in place.

**Comment by ericbsd** [comment]
After installation on the system?

**Comment by chatk7** [comment]
Yes. After successful installation on a Sandisk Flair flash drive. The installation dvd needed to be placed in the optical drive to boot the system on the flash drive. After the UEFI , it looked for the dvd or it would "failed...for line 0....." and asked for login without graphical interface. It then failed after correct login. 
I deleted Livemedia from the installation.

Pleae delete this email from the inBox and from the trash can after use.
If you are not the addresee, please delete this email immediately. No part of this email and/or atteachment is allowed for for-profit, public use.










 On Wednesday, September 15, 2021, 11:05:15 AM PDT, Eric Turgeon ***@***.***> wrote:










After installation on the system?



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ericbsd** [comment]
Sandisk Flair flash is a USB drive, and Installation is not supported for USB storage.

**Comment by ericbsd** [comment]
https://github.com/ghostbsd/gbi/issues/36

**Comment by chatk7** [comment]
System installation on USB storage may save the more expensive entire unit of pc from broken system.

**Comment by ericbsd** [comment]
Closing since it is a duplicate
