### ISSUE TITLE
[Bug]: GhostBSD 21.09.08 live can not start LightDM with AMD Thames [Radeon HD 7550M/7570M/7650M]

### ISSUE THREAD

**Issue by grahamperrin** [ghostbsd/ghostbsd-src#92]
### Describe the bug

An HP EliteBook 8570p that normally uses **radeonkms** (with FreeBSD 14.0-CURRENT) can not start LightDM when booting from a USB flash drive that was created from `GhostBSD-21.09.08.iso`: 

[Xorg.0.log](https://github.com/ghostbsd/ghostbsd-src/files/7149969/Xorg.0.log)

Probed: 

1. whilst running GhostBSD without the display manager <https://bsd-hardware.info/?probe=27f01061f2>
2. after the event, whilst running 14.0-CURRENT <https://bsd-hardware.info/?probe=5a4e53da56>

### How to reproduce the bug?

1. Write the `.iso` to a USB flash drive, e.g. `gdd status=progress bs=5M of=/dev/da0 if=GhostBSD-21.09.08.iso && sync`
2. boot from the drive
3. LightDM can not start

![image](https://user-images.githubusercontent.com/192271/132996142-ab971ad7-2481-445a-a6c8-4b46efe1ddd7.png)

### Expected behavior

3. LightDM should start.

**Comment by ericbsd** [comment]
Xconfig was loading amdgpu, instead of radeonkms.

This PR ghostbsd/xconfig#13 fixed the problem for other users.

**Comment by grahamperrin** [comment]
Thanks!
