### ISSUE TITLE
[Bug]: GhostBSD 21.09.08 ISO sha256 does not match

### ISSUE THREAD

**Issue by xscoops** [ghostbsd/ghostbsd-src#93]
### Describe the bug

Content of GhostBSD-21.09.08.iso.sha256 file does not match the output of the sha256sum command on ISO files downloaded from the United States and Canadian Mirror. I did not try the other mirrors.

Content of GhostBSD-21.09.08.iso.sha256:
SHA256 (GhostBSD-21.09.08.iso) = 8817bfaa249a10f8eeef8cf224687210b72ff149bebf1a45e907322f73065e7e

Output of sha256sum GhostBSD-21.09.08.iso
176b1b5f7cbd4db79c8c3f6f8636982b77af98011e98fccbcbddf2a45f5ba809  GhostBSD-21.09.08.iso

### How to reproduce the bug?

1. Download GhostBSD 21.09.08 ISO from the United States or Canadian Mirrors. https://www.ghostbsd.org/download
2. Download GhostBSD-21.09.08.iso.sha256.
3. Compare the content of GhostBSD-21.09.08.iso.sha256 and the output of the sha256sum command on the downloaded ISO file.

### Expected behavior

Checksums should match.

**Comment by ericbsd** [comment]
New build  not tested yet https://www.ghostbsd.org/download#latest_builds

**Comment by ericbsd** [comment]
21.09.29 https://www.ghostbsd.org/download
