### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by chatk7** [ghostbsd/ghostbsd-src#94]
### Describe the bug

updates on Sep23 of 21.09.12 build vanished the Xfce desktop and diabled intenet.

### How to reproduce the bug?

Installed it on Vostro 3990 desktop.

### Expected behavior

fixes.

**Comment by ericbsd** [comment]
You have to reinstall thunar, vlc, xfce4-desktop.
`sudo pkg install thunar vlc xfce4-desktop`

Instead of making a but reports for minor issues, ask the community first for help. The issue was fixed yesterday.
